// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

#include "base.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace idtxcore {
PROTOBUF_CONSTEXPR Handshake::Handshake(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.session_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.session_layer_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.usd_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.usd_uri_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HandshakeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HandshakeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HandshakeDefaultTypeInternal() {}
  union {
    Handshake _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HandshakeDefaultTypeInternal _Handshake_default_instance_;
PROTOBUF_CONSTEXPR BaseMessage::BaseMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.session_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct BaseMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BaseMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BaseMessageDefaultTypeInternal() {}
  union {
    BaseMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BaseMessageDefaultTypeInternal _BaseMessage_default_instance_;
}  // namespace idtxcore
static ::_pb::Metadata file_level_metadata_base_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_base_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_base_2eproto = nullptr;

const uint32_t TableStruct_base_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::idtxcore::Handshake, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::idtxcore::Handshake, _impl_.session_id_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Handshake, _impl_.session_layer_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Handshake, _impl_.usd_path_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Handshake, _impl_.usd_uri_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::BaseMessage, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::BaseMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::idtxcore::BaseMessage, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::idtxcore::BaseMessage, _impl_.session_id_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::idtxcore::BaseMessage, _impl_.message_),
  0,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::idtxcore::Handshake)},
  { 10, 23, -1, sizeof(::idtxcore::BaseMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::idtxcore::_Handshake_default_instance_._instance,
  &::idtxcore::_BaseMessage_default_instance_._instance,
};

const char descriptor_table_protodef_base_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nbase.proto\022\010idtxcore\032\017transform.proto\032"
  "\rsession.proto\"Y\n\tHandshake\022\022\n\nsession_i"
  "d\030\001 \001(\t\022\025\n\rsession_layer\030\002 \001(\t\022\020\n\010usd_pa"
  "th\030\003 \001(\t\022\017\n\007usd_uri\030\004 \001(\t\"\226\002\n\013BaseMessag"
  "e\022\027\n\nsession_id\030\001 \001(\tH\001\210\001\001\022(\n\thandshake\030"
  "\002 \001(\0132\023.idtxcore.HandshakeH\000\0221\n\014xform_up"
  "date\030\003 \001(\0132\031.idtxcore.TransformUpdateH\000\022"
  "7\n\017xform_broadcast\030\004 \001(\0132\034.idtxcore.Tran"
  "sformBroadcastH\000\022\034\n\003ack\030\005 \001(\0132\r.idtxcore"
  ".AckH\000\022 \n\005error\030\006 \001(\0132\017.idtxcore.ErrorH\000"
  "B\t\n\007messageB\r\n\013_session_idb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_base_2eproto_deps[2] = {
  &::descriptor_table_session_2eproto,
  &::descriptor_table_transform_2eproto,
};
static ::_pbi::once_flag descriptor_table_base_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_base_2eproto = {
    false, false, 434, descriptor_table_protodef_base_2eproto,
    "base.proto",
    &descriptor_table_base_2eproto_once, descriptor_table_base_2eproto_deps, 2, 2,
    schemas, file_default_instances, TableStruct_base_2eproto::offsets,
    file_level_metadata_base_2eproto, file_level_enum_descriptors_base_2eproto,
    file_level_service_descriptors_base_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_base_2eproto_getter() {
  return &descriptor_table_base_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_base_2eproto(&descriptor_table_base_2eproto);
namespace idtxcore {

// ===================================================================

class Handshake::_Internal {
 public:
};

Handshake::Handshake(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:idtxcore.Handshake)
}
Handshake::Handshake(const Handshake& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Handshake* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.session_id_){}
    , decltype(_impl_.session_layer_){}
    , decltype(_impl_.usd_path_){}
    , decltype(_impl_.usd_uri_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_session_id().empty()) {
    _this->_impl_.session_id_.Set(from._internal_session_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.session_layer_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_layer_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_session_layer().empty()) {
    _this->_impl_.session_layer_.Set(from._internal_session_layer(), 
      _this->GetArenaForAllocation());
  }
  _impl_.usd_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.usd_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_usd_path().empty()) {
    _this->_impl_.usd_path_.Set(from._internal_usd_path(), 
      _this->GetArenaForAllocation());
  }
  _impl_.usd_uri_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.usd_uri_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_usd_uri().empty()) {
    _this->_impl_.usd_uri_.Set(from._internal_usd_uri(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:idtxcore.Handshake)
}

inline void Handshake::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.session_id_){}
    , decltype(_impl_.session_layer_){}
    , decltype(_impl_.usd_path_){}
    , decltype(_impl_.usd_uri_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.session_layer_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_layer_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.usd_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.usd_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.usd_uri_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.usd_uri_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Handshake::~Handshake() {
  // @@protoc_insertion_point(destructor:idtxcore.Handshake)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Handshake::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.session_id_.Destroy();
  _impl_.session_layer_.Destroy();
  _impl_.usd_path_.Destroy();
  _impl_.usd_uri_.Destroy();
}

void Handshake::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Handshake::Clear() {
// @@protoc_insertion_point(message_clear_start:idtxcore.Handshake)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.session_id_.ClearToEmpty();
  _impl_.session_layer_.ClearToEmpty();
  _impl_.usd_path_.ClearToEmpty();
  _impl_.usd_uri_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Handshake::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string session_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_session_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "idtxcore.Handshake.session_id"));
        } else
          goto handle_unusual;
        continue;
      // string session_layer = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_session_layer();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "idtxcore.Handshake.session_layer"));
        } else
          goto handle_unusual;
        continue;
      // string usd_path = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_usd_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "idtxcore.Handshake.usd_path"));
        } else
          goto handle_unusual;
        continue;
      // string usd_uri = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_usd_uri();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "idtxcore.Handshake.usd_uri"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Handshake::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:idtxcore.Handshake)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string session_id = 1;
  if (!this->_internal_session_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_id().data(), static_cast<int>(this->_internal_session_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "idtxcore.Handshake.session_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_session_id(), target);
  }

  // string session_layer = 2;
  if (!this->_internal_session_layer().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_layer().data(), static_cast<int>(this->_internal_session_layer().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "idtxcore.Handshake.session_layer");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_session_layer(), target);
  }

  // string usd_path = 3;
  if (!this->_internal_usd_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_usd_path().data(), static_cast<int>(this->_internal_usd_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "idtxcore.Handshake.usd_path");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_usd_path(), target);
  }

  // string usd_uri = 4;
  if (!this->_internal_usd_uri().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_usd_uri().data(), static_cast<int>(this->_internal_usd_uri().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "idtxcore.Handshake.usd_uri");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_usd_uri(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:idtxcore.Handshake)
  return target;
}

size_t Handshake::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:idtxcore.Handshake)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string session_id = 1;
  if (!this->_internal_session_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_id());
  }

  // string session_layer = 2;
  if (!this->_internal_session_layer().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_layer());
  }

  // string usd_path = 3;
  if (!this->_internal_usd_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_usd_path());
  }

  // string usd_uri = 4;
  if (!this->_internal_usd_uri().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_usd_uri());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Handshake::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Handshake::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Handshake::GetClassData() const { return &_class_data_; }


void Handshake::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Handshake*>(&to_msg);
  auto& from = static_cast<const Handshake&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:idtxcore.Handshake)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_session_id().empty()) {
    _this->_internal_set_session_id(from._internal_session_id());
  }
  if (!from._internal_session_layer().empty()) {
    _this->_internal_set_session_layer(from._internal_session_layer());
  }
  if (!from._internal_usd_path().empty()) {
    _this->_internal_set_usd_path(from._internal_usd_path());
  }
  if (!from._internal_usd_uri().empty()) {
    _this->_internal_set_usd_uri(from._internal_usd_uri());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Handshake::CopyFrom(const Handshake& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:idtxcore.Handshake)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Handshake::IsInitialized() const {
  return true;
}

void Handshake::InternalSwap(Handshake* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.session_id_, lhs_arena,
      &other->_impl_.session_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.session_layer_, lhs_arena,
      &other->_impl_.session_layer_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.usd_path_, lhs_arena,
      &other->_impl_.usd_path_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.usd_uri_, lhs_arena,
      &other->_impl_.usd_uri_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Handshake::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_base_2eproto_getter, &descriptor_table_base_2eproto_once,
      file_level_metadata_base_2eproto[0]);
}

// ===================================================================

class BaseMessage::_Internal {
 public:
  using HasBits = decltype(std::declval<BaseMessage>()._impl_._has_bits_);
  static void set_has_session_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::idtxcore::Handshake& handshake(const BaseMessage* msg);
  static const ::idtxcore::TransformUpdate& xform_update(const BaseMessage* msg);
  static const ::idtxcore::TransformBroadcast& xform_broadcast(const BaseMessage* msg);
  static const ::idtxcore::Ack& ack(const BaseMessage* msg);
  static const ::idtxcore::Error& error(const BaseMessage* msg);
};

const ::idtxcore::Handshake&
BaseMessage::_Internal::handshake(const BaseMessage* msg) {
  return *msg->_impl_.message_.handshake_;
}
const ::idtxcore::TransformUpdate&
BaseMessage::_Internal::xform_update(const BaseMessage* msg) {
  return *msg->_impl_.message_.xform_update_;
}
const ::idtxcore::TransformBroadcast&
BaseMessage::_Internal::xform_broadcast(const BaseMessage* msg) {
  return *msg->_impl_.message_.xform_broadcast_;
}
const ::idtxcore::Ack&
BaseMessage::_Internal::ack(const BaseMessage* msg) {
  return *msg->_impl_.message_.ack_;
}
const ::idtxcore::Error&
BaseMessage::_Internal::error(const BaseMessage* msg) {
  return *msg->_impl_.message_.error_;
}
void BaseMessage::set_allocated_handshake(::idtxcore::Handshake* handshake) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_message();
  if (handshake) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(handshake);
    if (message_arena != submessage_arena) {
      handshake = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, handshake, submessage_arena);
    }
    set_has_handshake();
    _impl_.message_.handshake_ = handshake;
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.BaseMessage.handshake)
}
void BaseMessage::set_allocated_xform_update(::idtxcore::TransformUpdate* xform_update) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_message();
  if (xform_update) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(xform_update));
    if (message_arena != submessage_arena) {
      xform_update = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, xform_update, submessage_arena);
    }
    set_has_xform_update();
    _impl_.message_.xform_update_ = xform_update;
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.BaseMessage.xform_update)
}
void BaseMessage::clear_xform_update() {
  if (_internal_has_xform_update()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.message_.xform_update_;
    }
    clear_has_message();
  }
}
void BaseMessage::set_allocated_xform_broadcast(::idtxcore::TransformBroadcast* xform_broadcast) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_message();
  if (xform_broadcast) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(xform_broadcast));
    if (message_arena != submessage_arena) {
      xform_broadcast = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, xform_broadcast, submessage_arena);
    }
    set_has_xform_broadcast();
    _impl_.message_.xform_broadcast_ = xform_broadcast;
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.BaseMessage.xform_broadcast)
}
void BaseMessage::clear_xform_broadcast() {
  if (_internal_has_xform_broadcast()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.message_.xform_broadcast_;
    }
    clear_has_message();
  }
}
void BaseMessage::set_allocated_ack(::idtxcore::Ack* ack) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_message();
  if (ack) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(ack));
    if (message_arena != submessage_arena) {
      ack = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ack, submessage_arena);
    }
    set_has_ack();
    _impl_.message_.ack_ = ack;
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.BaseMessage.ack)
}
void BaseMessage::clear_ack() {
  if (_internal_has_ack()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.message_.ack_;
    }
    clear_has_message();
  }
}
void BaseMessage::set_allocated_error(::idtxcore::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_message();
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error));
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    set_has_error();
    _impl_.message_.error_ = error;
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.BaseMessage.error)
}
void BaseMessage::clear_error() {
  if (_internal_has_error()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.message_.error_;
    }
    clear_has_message();
  }
}
BaseMessage::BaseMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:idtxcore.BaseMessage)
}
BaseMessage::BaseMessage(const BaseMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BaseMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.session_id_){}
    , decltype(_impl_.message_){}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_session_id()) {
    _this->_impl_.session_id_.Set(from._internal_session_id(), 
      _this->GetArenaForAllocation());
  }
  clear_has_message();
  switch (from.message_case()) {
    case kHandshake: {
      _this->_internal_mutable_handshake()->::idtxcore::Handshake::MergeFrom(
          from._internal_handshake());
      break;
    }
    case kXformUpdate: {
      _this->_internal_mutable_xform_update()->::idtxcore::TransformUpdate::MergeFrom(
          from._internal_xform_update());
      break;
    }
    case kXformBroadcast: {
      _this->_internal_mutable_xform_broadcast()->::idtxcore::TransformBroadcast::MergeFrom(
          from._internal_xform_broadcast());
      break;
    }
    case kAck: {
      _this->_internal_mutable_ack()->::idtxcore::Ack::MergeFrom(
          from._internal_ack());
      break;
    }
    case kError: {
      _this->_internal_mutable_error()->::idtxcore::Error::MergeFrom(
          from._internal_error());
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:idtxcore.BaseMessage)
}

inline void BaseMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.session_id_){}
    , decltype(_impl_.message_){}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_message();
}

BaseMessage::~BaseMessage() {
  // @@protoc_insertion_point(destructor:idtxcore.BaseMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BaseMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.session_id_.Destroy();
  if (has_message()) {
    clear_message();
  }
}

void BaseMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BaseMessage::clear_message() {
// @@protoc_insertion_point(one_of_clear_start:idtxcore.BaseMessage)
  switch (message_case()) {
    case kHandshake: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.message_.handshake_;
      }
      break;
    }
    case kXformUpdate: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.message_.xform_update_;
      }
      break;
    }
    case kXformBroadcast: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.message_.xform_broadcast_;
      }
      break;
    }
    case kAck: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.message_.ack_;
      }
      break;
    }
    case kError: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.message_.error_;
      }
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = MESSAGE_NOT_SET;
}


void BaseMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:idtxcore.BaseMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.session_id_.ClearNonDefaultToEmpty();
  }
  clear_message();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BaseMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string session_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_session_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "idtxcore.BaseMessage.session_id"));
        } else
          goto handle_unusual;
        continue;
      // .idtxcore.Handshake handshake = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_handshake(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .idtxcore.TransformUpdate xform_update = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_xform_update(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .idtxcore.TransformBroadcast xform_broadcast = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_xform_broadcast(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .idtxcore.Ack ack = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_ack(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .idtxcore.Error error = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_error(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BaseMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:idtxcore.BaseMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional string session_id = 1;
  if (_internal_has_session_id()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_id().data(), static_cast<int>(this->_internal_session_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "idtxcore.BaseMessage.session_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_session_id(), target);
  }

  // .idtxcore.Handshake handshake = 2;
  if (_internal_has_handshake()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::handshake(this),
        _Internal::handshake(this).GetCachedSize(), target, stream);
  }

  // .idtxcore.TransformUpdate xform_update = 3;
  if (_internal_has_xform_update()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::xform_update(this),
        _Internal::xform_update(this).GetCachedSize(), target, stream);
  }

  // .idtxcore.TransformBroadcast xform_broadcast = 4;
  if (_internal_has_xform_broadcast()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::xform_broadcast(this),
        _Internal::xform_broadcast(this).GetCachedSize(), target, stream);
  }

  // .idtxcore.Ack ack = 5;
  if (_internal_has_ack()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::ack(this),
        _Internal::ack(this).GetCachedSize(), target, stream);
  }

  // .idtxcore.Error error = 6;
  if (_internal_has_error()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::error(this),
        _Internal::error(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:idtxcore.BaseMessage)
  return target;
}

size_t BaseMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:idtxcore.BaseMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string session_id = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_id());
  }

  switch (message_case()) {
    // .idtxcore.Handshake handshake = 2;
    case kHandshake: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.message_.handshake_);
      break;
    }
    // .idtxcore.TransformUpdate xform_update = 3;
    case kXformUpdate: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.message_.xform_update_);
      break;
    }
    // .idtxcore.TransformBroadcast xform_broadcast = 4;
    case kXformBroadcast: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.message_.xform_broadcast_);
      break;
    }
    // .idtxcore.Ack ack = 5;
    case kAck: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.message_.ack_);
      break;
    }
    // .idtxcore.Error error = 6;
    case kError: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.message_.error_);
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BaseMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BaseMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BaseMessage::GetClassData() const { return &_class_data_; }


void BaseMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BaseMessage*>(&to_msg);
  auto& from = static_cast<const BaseMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:idtxcore.BaseMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_session_id()) {
    _this->_internal_set_session_id(from._internal_session_id());
  }
  switch (from.message_case()) {
    case kHandshake: {
      _this->_internal_mutable_handshake()->::idtxcore::Handshake::MergeFrom(
          from._internal_handshake());
      break;
    }
    case kXformUpdate: {
      _this->_internal_mutable_xform_update()->::idtxcore::TransformUpdate::MergeFrom(
          from._internal_xform_update());
      break;
    }
    case kXformBroadcast: {
      _this->_internal_mutable_xform_broadcast()->::idtxcore::TransformBroadcast::MergeFrom(
          from._internal_xform_broadcast());
      break;
    }
    case kAck: {
      _this->_internal_mutable_ack()->::idtxcore::Ack::MergeFrom(
          from._internal_ack());
      break;
    }
    case kError: {
      _this->_internal_mutable_error()->::idtxcore::Error::MergeFrom(
          from._internal_error());
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BaseMessage::CopyFrom(const BaseMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:idtxcore.BaseMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BaseMessage::IsInitialized() const {
  return true;
}

void BaseMessage::InternalSwap(BaseMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.session_id_, lhs_arena,
      &other->_impl_.session_id_, rhs_arena
  );
  swap(_impl_.message_, other->_impl_.message_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata BaseMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_base_2eproto_getter, &descriptor_table_base_2eproto_once,
      file_level_metadata_base_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace idtxcore
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::idtxcore::Handshake*
Arena::CreateMaybeMessage< ::idtxcore::Handshake >(Arena* arena) {
  return Arena::CreateMessageInternal< ::idtxcore::Handshake >(arena);
}
template<> PROTOBUF_NOINLINE ::idtxcore::BaseMessage*
Arena::CreateMaybeMessage< ::idtxcore::BaseMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::idtxcore::BaseMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
