// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_base_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_base_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "transform.pb.h"
#include "session.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_base_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_base_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_base_2eproto;
namespace idtxcore {
class BaseMessage;
struct BaseMessageDefaultTypeInternal;
extern BaseMessageDefaultTypeInternal _BaseMessage_default_instance_;
class Handshake;
struct HandshakeDefaultTypeInternal;
extern HandshakeDefaultTypeInternal _Handshake_default_instance_;
}  // namespace idtxcore
PROTOBUF_NAMESPACE_OPEN
template<> ::idtxcore::BaseMessage* Arena::CreateMaybeMessage<::idtxcore::BaseMessage>(Arena*);
template<> ::idtxcore::Handshake* Arena::CreateMaybeMessage<::idtxcore::Handshake>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace idtxcore {

// ===================================================================

class Handshake final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:idtxcore.Handshake) */ {
 public:
  inline Handshake() : Handshake(nullptr) {}
  ~Handshake() override;
  explicit PROTOBUF_CONSTEXPR Handshake(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Handshake(const Handshake& from);
  Handshake(Handshake&& from) noexcept
    : Handshake() {
    *this = ::std::move(from);
  }

  inline Handshake& operator=(const Handshake& from) {
    CopyFrom(from);
    return *this;
  }
  inline Handshake& operator=(Handshake&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Handshake& default_instance() {
    return *internal_default_instance();
  }
  static inline const Handshake* internal_default_instance() {
    return reinterpret_cast<const Handshake*>(
               &_Handshake_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Handshake& a, Handshake& b) {
    a.Swap(&b);
  }
  inline void Swap(Handshake* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Handshake* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Handshake* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Handshake>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Handshake& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Handshake& from) {
    Handshake::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Handshake* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "idtxcore.Handshake";
  }
  protected:
  explicit Handshake(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionIdFieldNumber = 1,
    kSessionLayerFieldNumber = 2,
    kUsdPathFieldNumber = 3,
    kUsdUriFieldNumber = 4,
  };
  // string session_id = 1;
  void clear_session_id();
  const std::string& session_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_id();
  PROTOBUF_NODISCARD std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // string session_layer = 2;
  void clear_session_layer();
  const std::string& session_layer() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_layer(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_layer();
  PROTOBUF_NODISCARD std::string* release_session_layer();
  void set_allocated_session_layer(std::string* session_layer);
  private:
  const std::string& _internal_session_layer() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_layer(const std::string& value);
  std::string* _internal_mutable_session_layer();
  public:

  // string usd_path = 3;
  void clear_usd_path();
  const std::string& usd_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_usd_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_usd_path();
  PROTOBUF_NODISCARD std::string* release_usd_path();
  void set_allocated_usd_path(std::string* usd_path);
  private:
  const std::string& _internal_usd_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_usd_path(const std::string& value);
  std::string* _internal_mutable_usd_path();
  public:

  // string usd_uri = 4;
  void clear_usd_uri();
  const std::string& usd_uri() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_usd_uri(ArgT0&& arg0, ArgT... args);
  std::string* mutable_usd_uri();
  PROTOBUF_NODISCARD std::string* release_usd_uri();
  void set_allocated_usd_uri(std::string* usd_uri);
  private:
  const std::string& _internal_usd_uri() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_usd_uri(const std::string& value);
  std::string* _internal_mutable_usd_uri();
  public:

  // @@protoc_insertion_point(class_scope:idtxcore.Handshake)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_layer_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr usd_path_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr usd_uri_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_base_2eproto;
};
// -------------------------------------------------------------------

class BaseMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:idtxcore.BaseMessage) */ {
 public:
  inline BaseMessage() : BaseMessage(nullptr) {}
  ~BaseMessage() override;
  explicit PROTOBUF_CONSTEXPR BaseMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BaseMessage(const BaseMessage& from);
  BaseMessage(BaseMessage&& from) noexcept
    : BaseMessage() {
    *this = ::std::move(from);
  }

  inline BaseMessage& operator=(const BaseMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline BaseMessage& operator=(BaseMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BaseMessage& default_instance() {
    return *internal_default_instance();
  }
  enum MessageCase {
    kHandshake = 2,
    kXformUpdate = 3,
    kXformBroadcast = 4,
    kAck = 5,
    kError = 6,
    MESSAGE_NOT_SET = 0,
  };

  static inline const BaseMessage* internal_default_instance() {
    return reinterpret_cast<const BaseMessage*>(
               &_BaseMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BaseMessage& a, BaseMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(BaseMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BaseMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BaseMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BaseMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BaseMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BaseMessage& from) {
    BaseMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BaseMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "idtxcore.BaseMessage";
  }
  protected:
  explicit BaseMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionIdFieldNumber = 1,
    kHandshakeFieldNumber = 2,
    kXformUpdateFieldNumber = 3,
    kXformBroadcastFieldNumber = 4,
    kAckFieldNumber = 5,
    kErrorFieldNumber = 6,
  };
  // optional string session_id = 1;
  bool has_session_id() const;
  private:
  bool _internal_has_session_id() const;
  public:
  void clear_session_id();
  const std::string& session_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_id();
  PROTOBUF_NODISCARD std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // .idtxcore.Handshake handshake = 2;
  bool has_handshake() const;
  private:
  bool _internal_has_handshake() const;
  public:
  void clear_handshake();
  const ::idtxcore::Handshake& handshake() const;
  PROTOBUF_NODISCARD ::idtxcore::Handshake* release_handshake();
  ::idtxcore::Handshake* mutable_handshake();
  void set_allocated_handshake(::idtxcore::Handshake* handshake);
  private:
  const ::idtxcore::Handshake& _internal_handshake() const;
  ::idtxcore::Handshake* _internal_mutable_handshake();
  public:
  void unsafe_arena_set_allocated_handshake(
      ::idtxcore::Handshake* handshake);
  ::idtxcore::Handshake* unsafe_arena_release_handshake();

  // .idtxcore.TransformUpdate xform_update = 3;
  bool has_xform_update() const;
  private:
  bool _internal_has_xform_update() const;
  public:
  void clear_xform_update();
  const ::idtxcore::TransformUpdate& xform_update() const;
  PROTOBUF_NODISCARD ::idtxcore::TransformUpdate* release_xform_update();
  ::idtxcore::TransformUpdate* mutable_xform_update();
  void set_allocated_xform_update(::idtxcore::TransformUpdate* xform_update);
  private:
  const ::idtxcore::TransformUpdate& _internal_xform_update() const;
  ::idtxcore::TransformUpdate* _internal_mutable_xform_update();
  public:
  void unsafe_arena_set_allocated_xform_update(
      ::idtxcore::TransformUpdate* xform_update);
  ::idtxcore::TransformUpdate* unsafe_arena_release_xform_update();

  // .idtxcore.TransformBroadcast xform_broadcast = 4;
  bool has_xform_broadcast() const;
  private:
  bool _internal_has_xform_broadcast() const;
  public:
  void clear_xform_broadcast();
  const ::idtxcore::TransformBroadcast& xform_broadcast() const;
  PROTOBUF_NODISCARD ::idtxcore::TransformBroadcast* release_xform_broadcast();
  ::idtxcore::TransformBroadcast* mutable_xform_broadcast();
  void set_allocated_xform_broadcast(::idtxcore::TransformBroadcast* xform_broadcast);
  private:
  const ::idtxcore::TransformBroadcast& _internal_xform_broadcast() const;
  ::idtxcore::TransformBroadcast* _internal_mutable_xform_broadcast();
  public:
  void unsafe_arena_set_allocated_xform_broadcast(
      ::idtxcore::TransformBroadcast* xform_broadcast);
  ::idtxcore::TransformBroadcast* unsafe_arena_release_xform_broadcast();

  // .idtxcore.Ack ack = 5;
  bool has_ack() const;
  private:
  bool _internal_has_ack() const;
  public:
  void clear_ack();
  const ::idtxcore::Ack& ack() const;
  PROTOBUF_NODISCARD ::idtxcore::Ack* release_ack();
  ::idtxcore::Ack* mutable_ack();
  void set_allocated_ack(::idtxcore::Ack* ack);
  private:
  const ::idtxcore::Ack& _internal_ack() const;
  ::idtxcore::Ack* _internal_mutable_ack();
  public:
  void unsafe_arena_set_allocated_ack(
      ::idtxcore::Ack* ack);
  ::idtxcore::Ack* unsafe_arena_release_ack();

  // .idtxcore.Error error = 6;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  const ::idtxcore::Error& error() const;
  PROTOBUF_NODISCARD ::idtxcore::Error* release_error();
  ::idtxcore::Error* mutable_error();
  void set_allocated_error(::idtxcore::Error* error);
  private:
  const ::idtxcore::Error& _internal_error() const;
  ::idtxcore::Error* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::idtxcore::Error* error);
  ::idtxcore::Error* unsafe_arena_release_error();

  void clear_message();
  MessageCase message_case() const;
  // @@protoc_insertion_point(class_scope:idtxcore.BaseMessage)
 private:
  class _Internal;
  void set_has_handshake();
  void set_has_xform_update();
  void set_has_xform_broadcast();
  void set_has_ack();
  void set_has_error();

  inline bool has_message() const;
  inline void clear_has_message();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
    union MessageUnion {
      constexpr MessageUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::idtxcore::Handshake* handshake_;
      ::idtxcore::TransformUpdate* xform_update_;
      ::idtxcore::TransformBroadcast* xform_broadcast_;
      ::idtxcore::Ack* ack_;
      ::idtxcore::Error* error_;
    } message_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_base_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Handshake

// string session_id = 1;
inline void Handshake::clear_session_id() {
  _impl_.session_id_.ClearToEmpty();
}
inline const std::string& Handshake::session_id() const {
  // @@protoc_insertion_point(field_get:idtxcore.Handshake.session_id)
  return _internal_session_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Handshake::set_session_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.session_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:idtxcore.Handshake.session_id)
}
inline std::string* Handshake::mutable_session_id() {
  std::string* _s = _internal_mutable_session_id();
  // @@protoc_insertion_point(field_mutable:idtxcore.Handshake.session_id)
  return _s;
}
inline const std::string& Handshake::_internal_session_id() const {
  return _impl_.session_id_.Get();
}
inline void Handshake::_internal_set_session_id(const std::string& value) {
  
  _impl_.session_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Handshake::_internal_mutable_session_id() {
  
  return _impl_.session_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Handshake::release_session_id() {
  // @@protoc_insertion_point(field_release:idtxcore.Handshake.session_id)
  return _impl_.session_id_.Release();
}
inline void Handshake::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    
  } else {
    
  }
  _impl_.session_id_.SetAllocated(session_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:idtxcore.Handshake.session_id)
}

// string session_layer = 2;
inline void Handshake::clear_session_layer() {
  _impl_.session_layer_.ClearToEmpty();
}
inline const std::string& Handshake::session_layer() const {
  // @@protoc_insertion_point(field_get:idtxcore.Handshake.session_layer)
  return _internal_session_layer();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Handshake::set_session_layer(ArgT0&& arg0, ArgT... args) {
 
 _impl_.session_layer_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:idtxcore.Handshake.session_layer)
}
inline std::string* Handshake::mutable_session_layer() {
  std::string* _s = _internal_mutable_session_layer();
  // @@protoc_insertion_point(field_mutable:idtxcore.Handshake.session_layer)
  return _s;
}
inline const std::string& Handshake::_internal_session_layer() const {
  return _impl_.session_layer_.Get();
}
inline void Handshake::_internal_set_session_layer(const std::string& value) {
  
  _impl_.session_layer_.Set(value, GetArenaForAllocation());
}
inline std::string* Handshake::_internal_mutable_session_layer() {
  
  return _impl_.session_layer_.Mutable(GetArenaForAllocation());
}
inline std::string* Handshake::release_session_layer() {
  // @@protoc_insertion_point(field_release:idtxcore.Handshake.session_layer)
  return _impl_.session_layer_.Release();
}
inline void Handshake::set_allocated_session_layer(std::string* session_layer) {
  if (session_layer != nullptr) {
    
  } else {
    
  }
  _impl_.session_layer_.SetAllocated(session_layer, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_layer_.IsDefault()) {
    _impl_.session_layer_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:idtxcore.Handshake.session_layer)
}

// string usd_path = 3;
inline void Handshake::clear_usd_path() {
  _impl_.usd_path_.ClearToEmpty();
}
inline const std::string& Handshake::usd_path() const {
  // @@protoc_insertion_point(field_get:idtxcore.Handshake.usd_path)
  return _internal_usd_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Handshake::set_usd_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.usd_path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:idtxcore.Handshake.usd_path)
}
inline std::string* Handshake::mutable_usd_path() {
  std::string* _s = _internal_mutable_usd_path();
  // @@protoc_insertion_point(field_mutable:idtxcore.Handshake.usd_path)
  return _s;
}
inline const std::string& Handshake::_internal_usd_path() const {
  return _impl_.usd_path_.Get();
}
inline void Handshake::_internal_set_usd_path(const std::string& value) {
  
  _impl_.usd_path_.Set(value, GetArenaForAllocation());
}
inline std::string* Handshake::_internal_mutable_usd_path() {
  
  return _impl_.usd_path_.Mutable(GetArenaForAllocation());
}
inline std::string* Handshake::release_usd_path() {
  // @@protoc_insertion_point(field_release:idtxcore.Handshake.usd_path)
  return _impl_.usd_path_.Release();
}
inline void Handshake::set_allocated_usd_path(std::string* usd_path) {
  if (usd_path != nullptr) {
    
  } else {
    
  }
  _impl_.usd_path_.SetAllocated(usd_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.usd_path_.IsDefault()) {
    _impl_.usd_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:idtxcore.Handshake.usd_path)
}

// string usd_uri = 4;
inline void Handshake::clear_usd_uri() {
  _impl_.usd_uri_.ClearToEmpty();
}
inline const std::string& Handshake::usd_uri() const {
  // @@protoc_insertion_point(field_get:idtxcore.Handshake.usd_uri)
  return _internal_usd_uri();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Handshake::set_usd_uri(ArgT0&& arg0, ArgT... args) {
 
 _impl_.usd_uri_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:idtxcore.Handshake.usd_uri)
}
inline std::string* Handshake::mutable_usd_uri() {
  std::string* _s = _internal_mutable_usd_uri();
  // @@protoc_insertion_point(field_mutable:idtxcore.Handshake.usd_uri)
  return _s;
}
inline const std::string& Handshake::_internal_usd_uri() const {
  return _impl_.usd_uri_.Get();
}
inline void Handshake::_internal_set_usd_uri(const std::string& value) {
  
  _impl_.usd_uri_.Set(value, GetArenaForAllocation());
}
inline std::string* Handshake::_internal_mutable_usd_uri() {
  
  return _impl_.usd_uri_.Mutable(GetArenaForAllocation());
}
inline std::string* Handshake::release_usd_uri() {
  // @@protoc_insertion_point(field_release:idtxcore.Handshake.usd_uri)
  return _impl_.usd_uri_.Release();
}
inline void Handshake::set_allocated_usd_uri(std::string* usd_uri) {
  if (usd_uri != nullptr) {
    
  } else {
    
  }
  _impl_.usd_uri_.SetAllocated(usd_uri, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.usd_uri_.IsDefault()) {
    _impl_.usd_uri_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:idtxcore.Handshake.usd_uri)
}

// -------------------------------------------------------------------

// BaseMessage

// optional string session_id = 1;
inline bool BaseMessage::_internal_has_session_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool BaseMessage::has_session_id() const {
  return _internal_has_session_id();
}
inline void BaseMessage::clear_session_id() {
  _impl_.session_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& BaseMessage::session_id() const {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.session_id)
  return _internal_session_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BaseMessage::set_session_id(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.session_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:idtxcore.BaseMessage.session_id)
}
inline std::string* BaseMessage::mutable_session_id() {
  std::string* _s = _internal_mutable_session_id();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.session_id)
  return _s;
}
inline const std::string& BaseMessage::_internal_session_id() const {
  return _impl_.session_id_.Get();
}
inline void BaseMessage::_internal_set_session_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.session_id_.Set(value, GetArenaForAllocation());
}
inline std::string* BaseMessage::_internal_mutable_session_id() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.session_id_.Mutable(GetArenaForAllocation());
}
inline std::string* BaseMessage::release_session_id() {
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.session_id)
  if (!_internal_has_session_id()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.session_id_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void BaseMessage::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.session_id_.SetAllocated(session_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:idtxcore.BaseMessage.session_id)
}

// .idtxcore.Handshake handshake = 2;
inline bool BaseMessage::_internal_has_handshake() const {
  return message_case() == kHandshake;
}
inline bool BaseMessage::has_handshake() const {
  return _internal_has_handshake();
}
inline void BaseMessage::set_has_handshake() {
  _impl_._oneof_case_[0] = kHandshake;
}
inline void BaseMessage::clear_handshake() {
  if (_internal_has_handshake()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.message_.handshake_;
    }
    clear_has_message();
  }
}
inline ::idtxcore::Handshake* BaseMessage::release_handshake() {
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.handshake)
  if (_internal_has_handshake()) {
    clear_has_message();
    ::idtxcore::Handshake* temp = _impl_.message_.handshake_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.handshake_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::Handshake& BaseMessage::_internal_handshake() const {
  return _internal_has_handshake()
      ? *_impl_.message_.handshake_
      : reinterpret_cast< ::idtxcore::Handshake&>(::idtxcore::_Handshake_default_instance_);
}
inline const ::idtxcore::Handshake& BaseMessage::handshake() const {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.handshake)
  return _internal_handshake();
}
inline ::idtxcore::Handshake* BaseMessage::unsafe_arena_release_handshake() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.BaseMessage.handshake)
  if (_internal_has_handshake()) {
    clear_has_message();
    ::idtxcore::Handshake* temp = _impl_.message_.handshake_;
    _impl_.message_.handshake_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BaseMessage::unsafe_arena_set_allocated_handshake(::idtxcore::Handshake* handshake) {
  clear_message();
  if (handshake) {
    set_has_handshake();
    _impl_.message_.handshake_ = handshake;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.BaseMessage.handshake)
}
inline ::idtxcore::Handshake* BaseMessage::_internal_mutable_handshake() {
  if (!_internal_has_handshake()) {
    clear_message();
    set_has_handshake();
    _impl_.message_.handshake_ = CreateMaybeMessage< ::idtxcore::Handshake >(GetArenaForAllocation());
  }
  return _impl_.message_.handshake_;
}
inline ::idtxcore::Handshake* BaseMessage::mutable_handshake() {
  ::idtxcore::Handshake* _msg = _internal_mutable_handshake();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.handshake)
  return _msg;
}

// .idtxcore.TransformUpdate xform_update = 3;
inline bool BaseMessage::_internal_has_xform_update() const {
  return message_case() == kXformUpdate;
}
inline bool BaseMessage::has_xform_update() const {
  return _internal_has_xform_update();
}
inline void BaseMessage::set_has_xform_update() {
  _impl_._oneof_case_[0] = kXformUpdate;
}
inline ::idtxcore::TransformUpdate* BaseMessage::release_xform_update() {
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.xform_update)
  if (_internal_has_xform_update()) {
    clear_has_message();
    ::idtxcore::TransformUpdate* temp = _impl_.message_.xform_update_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.xform_update_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::TransformUpdate& BaseMessage::_internal_xform_update() const {
  return _internal_has_xform_update()
      ? *_impl_.message_.xform_update_
      : reinterpret_cast< ::idtxcore::TransformUpdate&>(::idtxcore::_TransformUpdate_default_instance_);
}
inline const ::idtxcore::TransformUpdate& BaseMessage::xform_update() const {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.xform_update)
  return _internal_xform_update();
}
inline ::idtxcore::TransformUpdate* BaseMessage::unsafe_arena_release_xform_update() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.BaseMessage.xform_update)
  if (_internal_has_xform_update()) {
    clear_has_message();
    ::idtxcore::TransformUpdate* temp = _impl_.message_.xform_update_;
    _impl_.message_.xform_update_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BaseMessage::unsafe_arena_set_allocated_xform_update(::idtxcore::TransformUpdate* xform_update) {
  clear_message();
  if (xform_update) {
    set_has_xform_update();
    _impl_.message_.xform_update_ = xform_update;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.BaseMessage.xform_update)
}
inline ::idtxcore::TransformUpdate* BaseMessage::_internal_mutable_xform_update() {
  if (!_internal_has_xform_update()) {
    clear_message();
    set_has_xform_update();
    _impl_.message_.xform_update_ = CreateMaybeMessage< ::idtxcore::TransformUpdate >(GetArenaForAllocation());
  }
  return _impl_.message_.xform_update_;
}
inline ::idtxcore::TransformUpdate* BaseMessage::mutable_xform_update() {
  ::idtxcore::TransformUpdate* _msg = _internal_mutable_xform_update();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.xform_update)
  return _msg;
}

// .idtxcore.TransformBroadcast xform_broadcast = 4;
inline bool BaseMessage::_internal_has_xform_broadcast() const {
  return message_case() == kXformBroadcast;
}
inline bool BaseMessage::has_xform_broadcast() const {
  return _internal_has_xform_broadcast();
}
inline void BaseMessage::set_has_xform_broadcast() {
  _impl_._oneof_case_[0] = kXformBroadcast;
}
inline ::idtxcore::TransformBroadcast* BaseMessage::release_xform_broadcast() {
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.xform_broadcast)
  if (_internal_has_xform_broadcast()) {
    clear_has_message();
    ::idtxcore::TransformBroadcast* temp = _impl_.message_.xform_broadcast_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.xform_broadcast_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::TransformBroadcast& BaseMessage::_internal_xform_broadcast() const {
  return _internal_has_xform_broadcast()
      ? *_impl_.message_.xform_broadcast_
      : reinterpret_cast< ::idtxcore::TransformBroadcast&>(::idtxcore::_TransformBroadcast_default_instance_);
}
inline const ::idtxcore::TransformBroadcast& BaseMessage::xform_broadcast() const {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.xform_broadcast)
  return _internal_xform_broadcast();
}
inline ::idtxcore::TransformBroadcast* BaseMessage::unsafe_arena_release_xform_broadcast() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.BaseMessage.xform_broadcast)
  if (_internal_has_xform_broadcast()) {
    clear_has_message();
    ::idtxcore::TransformBroadcast* temp = _impl_.message_.xform_broadcast_;
    _impl_.message_.xform_broadcast_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BaseMessage::unsafe_arena_set_allocated_xform_broadcast(::idtxcore::TransformBroadcast* xform_broadcast) {
  clear_message();
  if (xform_broadcast) {
    set_has_xform_broadcast();
    _impl_.message_.xform_broadcast_ = xform_broadcast;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.BaseMessage.xform_broadcast)
}
inline ::idtxcore::TransformBroadcast* BaseMessage::_internal_mutable_xform_broadcast() {
  if (!_internal_has_xform_broadcast()) {
    clear_message();
    set_has_xform_broadcast();
    _impl_.message_.xform_broadcast_ = CreateMaybeMessage< ::idtxcore::TransformBroadcast >(GetArenaForAllocation());
  }
  return _impl_.message_.xform_broadcast_;
}
inline ::idtxcore::TransformBroadcast* BaseMessage::mutable_xform_broadcast() {
  ::idtxcore::TransformBroadcast* _msg = _internal_mutable_xform_broadcast();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.xform_broadcast)
  return _msg;
}

// .idtxcore.Ack ack = 5;
inline bool BaseMessage::_internal_has_ack() const {
  return message_case() == kAck;
}
inline bool BaseMessage::has_ack() const {
  return _internal_has_ack();
}
inline void BaseMessage::set_has_ack() {
  _impl_._oneof_case_[0] = kAck;
}
inline ::idtxcore::Ack* BaseMessage::release_ack() {
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.ack)
  if (_internal_has_ack()) {
    clear_has_message();
    ::idtxcore::Ack* temp = _impl_.message_.ack_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.ack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::Ack& BaseMessage::_internal_ack() const {
  return _internal_has_ack()
      ? *_impl_.message_.ack_
      : reinterpret_cast< ::idtxcore::Ack&>(::idtxcore::_Ack_default_instance_);
}
inline const ::idtxcore::Ack& BaseMessage::ack() const {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.ack)
  return _internal_ack();
}
inline ::idtxcore::Ack* BaseMessage::unsafe_arena_release_ack() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.BaseMessage.ack)
  if (_internal_has_ack()) {
    clear_has_message();
    ::idtxcore::Ack* temp = _impl_.message_.ack_;
    _impl_.message_.ack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BaseMessage::unsafe_arena_set_allocated_ack(::idtxcore::Ack* ack) {
  clear_message();
  if (ack) {
    set_has_ack();
    _impl_.message_.ack_ = ack;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.BaseMessage.ack)
}
inline ::idtxcore::Ack* BaseMessage::_internal_mutable_ack() {
  if (!_internal_has_ack()) {
    clear_message();
    set_has_ack();
    _impl_.message_.ack_ = CreateMaybeMessage< ::idtxcore::Ack >(GetArenaForAllocation());
  }
  return _impl_.message_.ack_;
}
inline ::idtxcore::Ack* BaseMessage::mutable_ack() {
  ::idtxcore::Ack* _msg = _internal_mutable_ack();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.ack)
  return _msg;
}

// .idtxcore.Error error = 6;
inline bool BaseMessage::_internal_has_error() const {
  return message_case() == kError;
}
inline bool BaseMessage::has_error() const {
  return _internal_has_error();
}
inline void BaseMessage::set_has_error() {
  _impl_._oneof_case_[0] = kError;
}
inline ::idtxcore::Error* BaseMessage::release_error() {
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.error)
  if (_internal_has_error()) {
    clear_has_message();
    ::idtxcore::Error* temp = _impl_.message_.error_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::Error& BaseMessage::_internal_error() const {
  return _internal_has_error()
      ? *_impl_.message_.error_
      : reinterpret_cast< ::idtxcore::Error&>(::idtxcore::_Error_default_instance_);
}
inline const ::idtxcore::Error& BaseMessage::error() const {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.error)
  return _internal_error();
}
inline ::idtxcore::Error* BaseMessage::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.BaseMessage.error)
  if (_internal_has_error()) {
    clear_has_message();
    ::idtxcore::Error* temp = _impl_.message_.error_;
    _impl_.message_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BaseMessage::unsafe_arena_set_allocated_error(::idtxcore::Error* error) {
  clear_message();
  if (error) {
    set_has_error();
    _impl_.message_.error_ = error;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.BaseMessage.error)
}
inline ::idtxcore::Error* BaseMessage::_internal_mutable_error() {
  if (!_internal_has_error()) {
    clear_message();
    set_has_error();
    _impl_.message_.error_ = CreateMaybeMessage< ::idtxcore::Error >(GetArenaForAllocation());
  }
  return _impl_.message_.error_;
}
inline ::idtxcore::Error* BaseMessage::mutable_error() {
  ::idtxcore::Error* _msg = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.error)
  return _msg;
}

inline bool BaseMessage::has_message() const {
  return message_case() != MESSAGE_NOT_SET;
}
inline void BaseMessage::clear_has_message() {
  _impl_._oneof_case_[0] = MESSAGE_NOT_SET;
}
inline BaseMessage::MessageCase BaseMessage::message_case() const {
  return BaseMessage::MessageCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace idtxcore

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_base_2eproto
