// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transform.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_transform_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_transform_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_transform_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_transform_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_transform_2eproto;
namespace idtxcore {
class Matrix4dTransform;
struct Matrix4dTransformDefaultTypeInternal;
extern Matrix4dTransformDefaultTypeInternal _Matrix4dTransform_default_instance_;
class SeparateTransform;
struct SeparateTransformDefaultTypeInternal;
extern SeparateTransformDefaultTypeInternal _SeparateTransform_default_instance_;
class TransformBroadcast;
struct TransformBroadcastDefaultTypeInternal;
extern TransformBroadcastDefaultTypeInternal _TransformBroadcast_default_instance_;
class TransformUpdate;
struct TransformUpdateDefaultTypeInternal;
extern TransformUpdateDefaultTypeInternal _TransformUpdate_default_instance_;
class Vector3;
struct Vector3DefaultTypeInternal;
extern Vector3DefaultTypeInternal _Vector3_default_instance_;
}  // namespace idtxcore
PROTOBUF_NAMESPACE_OPEN
template<> ::idtxcore::Matrix4dTransform* Arena::CreateMaybeMessage<::idtxcore::Matrix4dTransform>(Arena*);
template<> ::idtxcore::SeparateTransform* Arena::CreateMaybeMessage<::idtxcore::SeparateTransform>(Arena*);
template<> ::idtxcore::TransformBroadcast* Arena::CreateMaybeMessage<::idtxcore::TransformBroadcast>(Arena*);
template<> ::idtxcore::TransformUpdate* Arena::CreateMaybeMessage<::idtxcore::TransformUpdate>(Arena*);
template<> ::idtxcore::Vector3* Arena::CreateMaybeMessage<::idtxcore::Vector3>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace idtxcore {

// ===================================================================

class Vector3 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:idtxcore.Vector3) */ {
 public:
  inline Vector3() : Vector3(nullptr) {}
  ~Vector3() override;
  explicit PROTOBUF_CONSTEXPR Vector3(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vector3(const Vector3& from);
  Vector3(Vector3&& from) noexcept
    : Vector3() {
    *this = ::std::move(from);
  }

  inline Vector3& operator=(const Vector3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3& operator=(Vector3&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vector3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vector3* internal_default_instance() {
    return reinterpret_cast<const Vector3*>(
               &_Vector3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vector3& a, Vector3& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector3* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vector3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vector3>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vector3& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Vector3& from) {
    Vector3::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "idtxcore.Vector3";
  }
  protected:
  explicit Vector3(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 3;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:idtxcore.Vector3)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double x_;
    double y_;
    double z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transform_2eproto;
};
// -------------------------------------------------------------------

class Matrix4dTransform final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:idtxcore.Matrix4dTransform) */ {
 public:
  inline Matrix4dTransform() : Matrix4dTransform(nullptr) {}
  ~Matrix4dTransform() override;
  explicit PROTOBUF_CONSTEXPR Matrix4dTransform(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Matrix4dTransform(const Matrix4dTransform& from);
  Matrix4dTransform(Matrix4dTransform&& from) noexcept
    : Matrix4dTransform() {
    *this = ::std::move(from);
  }

  inline Matrix4dTransform& operator=(const Matrix4dTransform& from) {
    CopyFrom(from);
    return *this;
  }
  inline Matrix4dTransform& operator=(Matrix4dTransform&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Matrix4dTransform& default_instance() {
    return *internal_default_instance();
  }
  static inline const Matrix4dTransform* internal_default_instance() {
    return reinterpret_cast<const Matrix4dTransform*>(
               &_Matrix4dTransform_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Matrix4dTransform& a, Matrix4dTransform& b) {
    a.Swap(&b);
  }
  inline void Swap(Matrix4dTransform* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Matrix4dTransform* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Matrix4dTransform* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Matrix4dTransform>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Matrix4dTransform& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Matrix4dTransform& from) {
    Matrix4dTransform::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Matrix4dTransform* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "idtxcore.Matrix4dTransform";
  }
  protected:
  explicit Matrix4dTransform(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kM00FieldNumber = 1,
    kM01FieldNumber = 2,
    kM02FieldNumber = 3,
    kM03FieldNumber = 4,
    kM10FieldNumber = 5,
    kM11FieldNumber = 6,
    kM12FieldNumber = 7,
    kM13FieldNumber = 8,
    kM20FieldNumber = 9,
    kM21FieldNumber = 10,
    kM22FieldNumber = 11,
    kM23FieldNumber = 12,
    kM30FieldNumber = 13,
    kM31FieldNumber = 14,
    kM32FieldNumber = 15,
    kM33FieldNumber = 16,
  };
  // double m00 = 1;
  void clear_m00();
  double m00() const;
  void set_m00(double value);
  private:
  double _internal_m00() const;
  void _internal_set_m00(double value);
  public:

  // double m01 = 2;
  void clear_m01();
  double m01() const;
  void set_m01(double value);
  private:
  double _internal_m01() const;
  void _internal_set_m01(double value);
  public:

  // double m02 = 3;
  void clear_m02();
  double m02() const;
  void set_m02(double value);
  private:
  double _internal_m02() const;
  void _internal_set_m02(double value);
  public:

  // double m03 = 4;
  void clear_m03();
  double m03() const;
  void set_m03(double value);
  private:
  double _internal_m03() const;
  void _internal_set_m03(double value);
  public:

  // double m10 = 5;
  void clear_m10();
  double m10() const;
  void set_m10(double value);
  private:
  double _internal_m10() const;
  void _internal_set_m10(double value);
  public:

  // double m11 = 6;
  void clear_m11();
  double m11() const;
  void set_m11(double value);
  private:
  double _internal_m11() const;
  void _internal_set_m11(double value);
  public:

  // double m12 = 7;
  void clear_m12();
  double m12() const;
  void set_m12(double value);
  private:
  double _internal_m12() const;
  void _internal_set_m12(double value);
  public:

  // double m13 = 8;
  void clear_m13();
  double m13() const;
  void set_m13(double value);
  private:
  double _internal_m13() const;
  void _internal_set_m13(double value);
  public:

  // double m20 = 9;
  void clear_m20();
  double m20() const;
  void set_m20(double value);
  private:
  double _internal_m20() const;
  void _internal_set_m20(double value);
  public:

  // double m21 = 10;
  void clear_m21();
  double m21() const;
  void set_m21(double value);
  private:
  double _internal_m21() const;
  void _internal_set_m21(double value);
  public:

  // double m22 = 11;
  void clear_m22();
  double m22() const;
  void set_m22(double value);
  private:
  double _internal_m22() const;
  void _internal_set_m22(double value);
  public:

  // double m23 = 12;
  void clear_m23();
  double m23() const;
  void set_m23(double value);
  private:
  double _internal_m23() const;
  void _internal_set_m23(double value);
  public:

  // double m30 = 13;
  void clear_m30();
  double m30() const;
  void set_m30(double value);
  private:
  double _internal_m30() const;
  void _internal_set_m30(double value);
  public:

  // double m31 = 14;
  void clear_m31();
  double m31() const;
  void set_m31(double value);
  private:
  double _internal_m31() const;
  void _internal_set_m31(double value);
  public:

  // double m32 = 15;
  void clear_m32();
  double m32() const;
  void set_m32(double value);
  private:
  double _internal_m32() const;
  void _internal_set_m32(double value);
  public:

  // double m33 = 16;
  void clear_m33();
  double m33() const;
  void set_m33(double value);
  private:
  double _internal_m33() const;
  void _internal_set_m33(double value);
  public:

  // @@protoc_insertion_point(class_scope:idtxcore.Matrix4dTransform)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double m00_;
    double m01_;
    double m02_;
    double m03_;
    double m10_;
    double m11_;
    double m12_;
    double m13_;
    double m20_;
    double m21_;
    double m22_;
    double m23_;
    double m30_;
    double m31_;
    double m32_;
    double m33_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transform_2eproto;
};
// -------------------------------------------------------------------

class SeparateTransform final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:idtxcore.SeparateTransform) */ {
 public:
  inline SeparateTransform() : SeparateTransform(nullptr) {}
  ~SeparateTransform() override;
  explicit PROTOBUF_CONSTEXPR SeparateTransform(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SeparateTransform(const SeparateTransform& from);
  SeparateTransform(SeparateTransform&& from) noexcept
    : SeparateTransform() {
    *this = ::std::move(from);
  }

  inline SeparateTransform& operator=(const SeparateTransform& from) {
    CopyFrom(from);
    return *this;
  }
  inline SeparateTransform& operator=(SeparateTransform&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SeparateTransform& default_instance() {
    return *internal_default_instance();
  }
  static inline const SeparateTransform* internal_default_instance() {
    return reinterpret_cast<const SeparateTransform*>(
               &_SeparateTransform_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SeparateTransform& a, SeparateTransform& b) {
    a.Swap(&b);
  }
  inline void Swap(SeparateTransform* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SeparateTransform* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SeparateTransform* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SeparateTransform>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SeparateTransform& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SeparateTransform& from) {
    SeparateTransform::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SeparateTransform* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "idtxcore.SeparateTransform";
  }
  protected:
  explicit SeparateTransform(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTranslationFieldNumber = 1,
    kRotationFieldNumber = 2,
    kScaleFieldNumber = 3,
  };
  // .idtxcore.Vector3 translation = 1;
  bool has_translation() const;
  private:
  bool _internal_has_translation() const;
  public:
  void clear_translation();
  const ::idtxcore::Vector3& translation() const;
  PROTOBUF_NODISCARD ::idtxcore::Vector3* release_translation();
  ::idtxcore::Vector3* mutable_translation();
  void set_allocated_translation(::idtxcore::Vector3* translation);
  private:
  const ::idtxcore::Vector3& _internal_translation() const;
  ::idtxcore::Vector3* _internal_mutable_translation();
  public:
  void unsafe_arena_set_allocated_translation(
      ::idtxcore::Vector3* translation);
  ::idtxcore::Vector3* unsafe_arena_release_translation();

  // .idtxcore.Vector3 rotation = 2;
  bool has_rotation() const;
  private:
  bool _internal_has_rotation() const;
  public:
  void clear_rotation();
  const ::idtxcore::Vector3& rotation() const;
  PROTOBUF_NODISCARD ::idtxcore::Vector3* release_rotation();
  ::idtxcore::Vector3* mutable_rotation();
  void set_allocated_rotation(::idtxcore::Vector3* rotation);
  private:
  const ::idtxcore::Vector3& _internal_rotation() const;
  ::idtxcore::Vector3* _internal_mutable_rotation();
  public:
  void unsafe_arena_set_allocated_rotation(
      ::idtxcore::Vector3* rotation);
  ::idtxcore::Vector3* unsafe_arena_release_rotation();

  // .idtxcore.Vector3 scale = 3;
  bool has_scale() const;
  private:
  bool _internal_has_scale() const;
  public:
  void clear_scale();
  const ::idtxcore::Vector3& scale() const;
  PROTOBUF_NODISCARD ::idtxcore::Vector3* release_scale();
  ::idtxcore::Vector3* mutable_scale();
  void set_allocated_scale(::idtxcore::Vector3* scale);
  private:
  const ::idtxcore::Vector3& _internal_scale() const;
  ::idtxcore::Vector3* _internal_mutable_scale();
  public:
  void unsafe_arena_set_allocated_scale(
      ::idtxcore::Vector3* scale);
  ::idtxcore::Vector3* unsafe_arena_release_scale();

  // @@protoc_insertion_point(class_scope:idtxcore.SeparateTransform)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::idtxcore::Vector3* translation_;
    ::idtxcore::Vector3* rotation_;
    ::idtxcore::Vector3* scale_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transform_2eproto;
};
// -------------------------------------------------------------------

class TransformUpdate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:idtxcore.TransformUpdate) */ {
 public:
  inline TransformUpdate() : TransformUpdate(nullptr) {}
  ~TransformUpdate() override;
  explicit PROTOBUF_CONSTEXPR TransformUpdate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TransformUpdate(const TransformUpdate& from);
  TransformUpdate(TransformUpdate&& from) noexcept
    : TransformUpdate() {
    *this = ::std::move(from);
  }

  inline TransformUpdate& operator=(const TransformUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransformUpdate& operator=(TransformUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TransformUpdate& default_instance() {
    return *internal_default_instance();
  }
  enum TransformCase {
    kSeperate = 4,
    kMatrix = 5,
    TRANSFORM_NOT_SET = 0,
  };

  static inline const TransformUpdate* internal_default_instance() {
    return reinterpret_cast<const TransformUpdate*>(
               &_TransformUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(TransformUpdate& a, TransformUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(TransformUpdate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransformUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TransformUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TransformUpdate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TransformUpdate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TransformUpdate& from) {
    TransformUpdate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransformUpdate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "idtxcore.TransformUpdate";
  }
  protected:
  explicit TransformUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionIdFieldNumber = 1,
    kUsdFileFieldNumber = 2,
    kPrimPathFieldNumber = 3,
    kTimestampFieldNumber = 7,
    kSeperateFieldNumber = 4,
    kMatrixFieldNumber = 5,
  };
  // string session_id = 1;
  void clear_session_id();
  const std::string& session_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_id();
  PROTOBUF_NODISCARD std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // string usd_file = 2;
  void clear_usd_file();
  const std::string& usd_file() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_usd_file(ArgT0&& arg0, ArgT... args);
  std::string* mutable_usd_file();
  PROTOBUF_NODISCARD std::string* release_usd_file();
  void set_allocated_usd_file(std::string* usd_file);
  private:
  const std::string& _internal_usd_file() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_usd_file(const std::string& value);
  std::string* _internal_mutable_usd_file();
  public:

  // string prim_path = 3;
  void clear_prim_path();
  const std::string& prim_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_prim_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_prim_path();
  PROTOBUF_NODISCARD std::string* release_prim_path();
  void set_allocated_prim_path(std::string* prim_path);
  private:
  const std::string& _internal_prim_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prim_path(const std::string& value);
  std::string* _internal_mutable_prim_path();
  public:

  // int64 timestamp = 7;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // .idtxcore.SeparateTransform seperate = 4;
  bool has_seperate() const;
  private:
  bool _internal_has_seperate() const;
  public:
  void clear_seperate();
  const ::idtxcore::SeparateTransform& seperate() const;
  PROTOBUF_NODISCARD ::idtxcore::SeparateTransform* release_seperate();
  ::idtxcore::SeparateTransform* mutable_seperate();
  void set_allocated_seperate(::idtxcore::SeparateTransform* seperate);
  private:
  const ::idtxcore::SeparateTransform& _internal_seperate() const;
  ::idtxcore::SeparateTransform* _internal_mutable_seperate();
  public:
  void unsafe_arena_set_allocated_seperate(
      ::idtxcore::SeparateTransform* seperate);
  ::idtxcore::SeparateTransform* unsafe_arena_release_seperate();

  // .idtxcore.Matrix4dTransform matrix = 5;
  bool has_matrix() const;
  private:
  bool _internal_has_matrix() const;
  public:
  void clear_matrix();
  const ::idtxcore::Matrix4dTransform& matrix() const;
  PROTOBUF_NODISCARD ::idtxcore::Matrix4dTransform* release_matrix();
  ::idtxcore::Matrix4dTransform* mutable_matrix();
  void set_allocated_matrix(::idtxcore::Matrix4dTransform* matrix);
  private:
  const ::idtxcore::Matrix4dTransform& _internal_matrix() const;
  ::idtxcore::Matrix4dTransform* _internal_mutable_matrix();
  public:
  void unsafe_arena_set_allocated_matrix(
      ::idtxcore::Matrix4dTransform* matrix);
  ::idtxcore::Matrix4dTransform* unsafe_arena_release_matrix();

  void clear_transform();
  TransformCase transform_case() const;
  // @@protoc_insertion_point(class_scope:idtxcore.TransformUpdate)
 private:
  class _Internal;
  void set_has_seperate();
  void set_has_matrix();

  inline bool has_transform() const;
  inline void clear_has_transform();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr usd_file_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr prim_path_;
    int64_t timestamp_;
    union TransformUnion {
      constexpr TransformUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::idtxcore::SeparateTransform* seperate_;
      ::idtxcore::Matrix4dTransform* matrix_;
    } transform_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transform_2eproto;
};
// -------------------------------------------------------------------

class TransformBroadcast final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:idtxcore.TransformBroadcast) */ {
 public:
  inline TransformBroadcast() : TransformBroadcast(nullptr) {}
  ~TransformBroadcast() override;
  explicit PROTOBUF_CONSTEXPR TransformBroadcast(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TransformBroadcast(const TransformBroadcast& from);
  TransformBroadcast(TransformBroadcast&& from) noexcept
    : TransformBroadcast() {
    *this = ::std::move(from);
  }

  inline TransformBroadcast& operator=(const TransformBroadcast& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransformBroadcast& operator=(TransformBroadcast&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TransformBroadcast& default_instance() {
    return *internal_default_instance();
  }
  static inline const TransformBroadcast* internal_default_instance() {
    return reinterpret_cast<const TransformBroadcast*>(
               &_TransformBroadcast_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(TransformBroadcast& a, TransformBroadcast& b) {
    a.Swap(&b);
  }
  inline void Swap(TransformBroadcast* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransformBroadcast* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TransformBroadcast* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TransformBroadcast>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TransformBroadcast& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TransformBroadcast& from) {
    TransformBroadcast::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransformBroadcast* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "idtxcore.TransformBroadcast";
  }
  protected:
  explicit TransformBroadcast(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 1,
    kUpdateFieldNumber = 2,
  };
  // string client_id = 1;
  void clear_client_id();
  const std::string& client_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_client_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_client_id();
  PROTOBUF_NODISCARD std::string* release_client_id();
  void set_allocated_client_id(std::string* client_id);
  private:
  const std::string& _internal_client_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_id(const std::string& value);
  std::string* _internal_mutable_client_id();
  public:

  // .idtxcore.TransformUpdate update = 2;
  bool has_update() const;
  private:
  bool _internal_has_update() const;
  public:
  void clear_update();
  const ::idtxcore::TransformUpdate& update() const;
  PROTOBUF_NODISCARD ::idtxcore::TransformUpdate* release_update();
  ::idtxcore::TransformUpdate* mutable_update();
  void set_allocated_update(::idtxcore::TransformUpdate* update);
  private:
  const ::idtxcore::TransformUpdate& _internal_update() const;
  ::idtxcore::TransformUpdate* _internal_mutable_update();
  public:
  void unsafe_arena_set_allocated_update(
      ::idtxcore::TransformUpdate* update);
  ::idtxcore::TransformUpdate* unsafe_arena_release_update();

  // @@protoc_insertion_point(class_scope:idtxcore.TransformBroadcast)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_id_;
    ::idtxcore::TransformUpdate* update_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transform_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vector3

// double x = 1;
inline void Vector3::clear_x() {
  _impl_.x_ = 0;
}
inline double Vector3::_internal_x() const {
  return _impl_.x_;
}
inline double Vector3::x() const {
  // @@protoc_insertion_point(field_get:idtxcore.Vector3.x)
  return _internal_x();
}
inline void Vector3::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void Vector3::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:idtxcore.Vector3.x)
}

// double y = 2;
inline void Vector3::clear_y() {
  _impl_.y_ = 0;
}
inline double Vector3::_internal_y() const {
  return _impl_.y_;
}
inline double Vector3::y() const {
  // @@protoc_insertion_point(field_get:idtxcore.Vector3.y)
  return _internal_y();
}
inline void Vector3::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void Vector3::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:idtxcore.Vector3.y)
}

// double z = 3;
inline void Vector3::clear_z() {
  _impl_.z_ = 0;
}
inline double Vector3::_internal_z() const {
  return _impl_.z_;
}
inline double Vector3::z() const {
  // @@protoc_insertion_point(field_get:idtxcore.Vector3.z)
  return _internal_z();
}
inline void Vector3::_internal_set_z(double value) {
  
  _impl_.z_ = value;
}
inline void Vector3::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:idtxcore.Vector3.z)
}

// -------------------------------------------------------------------

// Matrix4dTransform

// double m00 = 1;
inline void Matrix4dTransform::clear_m00() {
  _impl_.m00_ = 0;
}
inline double Matrix4dTransform::_internal_m00() const {
  return _impl_.m00_;
}
inline double Matrix4dTransform::m00() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m00)
  return _internal_m00();
}
inline void Matrix4dTransform::_internal_set_m00(double value) {
  
  _impl_.m00_ = value;
}
inline void Matrix4dTransform::set_m00(double value) {
  _internal_set_m00(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m00)
}

// double m01 = 2;
inline void Matrix4dTransform::clear_m01() {
  _impl_.m01_ = 0;
}
inline double Matrix4dTransform::_internal_m01() const {
  return _impl_.m01_;
}
inline double Matrix4dTransform::m01() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m01)
  return _internal_m01();
}
inline void Matrix4dTransform::_internal_set_m01(double value) {
  
  _impl_.m01_ = value;
}
inline void Matrix4dTransform::set_m01(double value) {
  _internal_set_m01(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m01)
}

// double m02 = 3;
inline void Matrix4dTransform::clear_m02() {
  _impl_.m02_ = 0;
}
inline double Matrix4dTransform::_internal_m02() const {
  return _impl_.m02_;
}
inline double Matrix4dTransform::m02() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m02)
  return _internal_m02();
}
inline void Matrix4dTransform::_internal_set_m02(double value) {
  
  _impl_.m02_ = value;
}
inline void Matrix4dTransform::set_m02(double value) {
  _internal_set_m02(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m02)
}

// double m03 = 4;
inline void Matrix4dTransform::clear_m03() {
  _impl_.m03_ = 0;
}
inline double Matrix4dTransform::_internal_m03() const {
  return _impl_.m03_;
}
inline double Matrix4dTransform::m03() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m03)
  return _internal_m03();
}
inline void Matrix4dTransform::_internal_set_m03(double value) {
  
  _impl_.m03_ = value;
}
inline void Matrix4dTransform::set_m03(double value) {
  _internal_set_m03(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m03)
}

// double m10 = 5;
inline void Matrix4dTransform::clear_m10() {
  _impl_.m10_ = 0;
}
inline double Matrix4dTransform::_internal_m10() const {
  return _impl_.m10_;
}
inline double Matrix4dTransform::m10() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m10)
  return _internal_m10();
}
inline void Matrix4dTransform::_internal_set_m10(double value) {
  
  _impl_.m10_ = value;
}
inline void Matrix4dTransform::set_m10(double value) {
  _internal_set_m10(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m10)
}

// double m11 = 6;
inline void Matrix4dTransform::clear_m11() {
  _impl_.m11_ = 0;
}
inline double Matrix4dTransform::_internal_m11() const {
  return _impl_.m11_;
}
inline double Matrix4dTransform::m11() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m11)
  return _internal_m11();
}
inline void Matrix4dTransform::_internal_set_m11(double value) {
  
  _impl_.m11_ = value;
}
inline void Matrix4dTransform::set_m11(double value) {
  _internal_set_m11(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m11)
}

// double m12 = 7;
inline void Matrix4dTransform::clear_m12() {
  _impl_.m12_ = 0;
}
inline double Matrix4dTransform::_internal_m12() const {
  return _impl_.m12_;
}
inline double Matrix4dTransform::m12() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m12)
  return _internal_m12();
}
inline void Matrix4dTransform::_internal_set_m12(double value) {
  
  _impl_.m12_ = value;
}
inline void Matrix4dTransform::set_m12(double value) {
  _internal_set_m12(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m12)
}

// double m13 = 8;
inline void Matrix4dTransform::clear_m13() {
  _impl_.m13_ = 0;
}
inline double Matrix4dTransform::_internal_m13() const {
  return _impl_.m13_;
}
inline double Matrix4dTransform::m13() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m13)
  return _internal_m13();
}
inline void Matrix4dTransform::_internal_set_m13(double value) {
  
  _impl_.m13_ = value;
}
inline void Matrix4dTransform::set_m13(double value) {
  _internal_set_m13(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m13)
}

// double m20 = 9;
inline void Matrix4dTransform::clear_m20() {
  _impl_.m20_ = 0;
}
inline double Matrix4dTransform::_internal_m20() const {
  return _impl_.m20_;
}
inline double Matrix4dTransform::m20() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m20)
  return _internal_m20();
}
inline void Matrix4dTransform::_internal_set_m20(double value) {
  
  _impl_.m20_ = value;
}
inline void Matrix4dTransform::set_m20(double value) {
  _internal_set_m20(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m20)
}

// double m21 = 10;
inline void Matrix4dTransform::clear_m21() {
  _impl_.m21_ = 0;
}
inline double Matrix4dTransform::_internal_m21() const {
  return _impl_.m21_;
}
inline double Matrix4dTransform::m21() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m21)
  return _internal_m21();
}
inline void Matrix4dTransform::_internal_set_m21(double value) {
  
  _impl_.m21_ = value;
}
inline void Matrix4dTransform::set_m21(double value) {
  _internal_set_m21(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m21)
}

// double m22 = 11;
inline void Matrix4dTransform::clear_m22() {
  _impl_.m22_ = 0;
}
inline double Matrix4dTransform::_internal_m22() const {
  return _impl_.m22_;
}
inline double Matrix4dTransform::m22() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m22)
  return _internal_m22();
}
inline void Matrix4dTransform::_internal_set_m22(double value) {
  
  _impl_.m22_ = value;
}
inline void Matrix4dTransform::set_m22(double value) {
  _internal_set_m22(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m22)
}

// double m23 = 12;
inline void Matrix4dTransform::clear_m23() {
  _impl_.m23_ = 0;
}
inline double Matrix4dTransform::_internal_m23() const {
  return _impl_.m23_;
}
inline double Matrix4dTransform::m23() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m23)
  return _internal_m23();
}
inline void Matrix4dTransform::_internal_set_m23(double value) {
  
  _impl_.m23_ = value;
}
inline void Matrix4dTransform::set_m23(double value) {
  _internal_set_m23(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m23)
}

// double m30 = 13;
inline void Matrix4dTransform::clear_m30() {
  _impl_.m30_ = 0;
}
inline double Matrix4dTransform::_internal_m30() const {
  return _impl_.m30_;
}
inline double Matrix4dTransform::m30() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m30)
  return _internal_m30();
}
inline void Matrix4dTransform::_internal_set_m30(double value) {
  
  _impl_.m30_ = value;
}
inline void Matrix4dTransform::set_m30(double value) {
  _internal_set_m30(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m30)
}

// double m31 = 14;
inline void Matrix4dTransform::clear_m31() {
  _impl_.m31_ = 0;
}
inline double Matrix4dTransform::_internal_m31() const {
  return _impl_.m31_;
}
inline double Matrix4dTransform::m31() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m31)
  return _internal_m31();
}
inline void Matrix4dTransform::_internal_set_m31(double value) {
  
  _impl_.m31_ = value;
}
inline void Matrix4dTransform::set_m31(double value) {
  _internal_set_m31(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m31)
}

// double m32 = 15;
inline void Matrix4dTransform::clear_m32() {
  _impl_.m32_ = 0;
}
inline double Matrix4dTransform::_internal_m32() const {
  return _impl_.m32_;
}
inline double Matrix4dTransform::m32() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m32)
  return _internal_m32();
}
inline void Matrix4dTransform::_internal_set_m32(double value) {
  
  _impl_.m32_ = value;
}
inline void Matrix4dTransform::set_m32(double value) {
  _internal_set_m32(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m32)
}

// double m33 = 16;
inline void Matrix4dTransform::clear_m33() {
  _impl_.m33_ = 0;
}
inline double Matrix4dTransform::_internal_m33() const {
  return _impl_.m33_;
}
inline double Matrix4dTransform::m33() const {
  // @@protoc_insertion_point(field_get:idtxcore.Matrix4dTransform.m33)
  return _internal_m33();
}
inline void Matrix4dTransform::_internal_set_m33(double value) {
  
  _impl_.m33_ = value;
}
inline void Matrix4dTransform::set_m33(double value) {
  _internal_set_m33(value);
  // @@protoc_insertion_point(field_set:idtxcore.Matrix4dTransform.m33)
}

// -------------------------------------------------------------------

// SeparateTransform

// .idtxcore.Vector3 translation = 1;
inline bool SeparateTransform::_internal_has_translation() const {
  return this != internal_default_instance() && _impl_.translation_ != nullptr;
}
inline bool SeparateTransform::has_translation() const {
  return _internal_has_translation();
}
inline void SeparateTransform::clear_translation() {
  if (GetArenaForAllocation() == nullptr && _impl_.translation_ != nullptr) {
    delete _impl_.translation_;
  }
  _impl_.translation_ = nullptr;
}
inline const ::idtxcore::Vector3& SeparateTransform::_internal_translation() const {
  const ::idtxcore::Vector3* p = _impl_.translation_;
  return p != nullptr ? *p : reinterpret_cast<const ::idtxcore::Vector3&>(
      ::idtxcore::_Vector3_default_instance_);
}
inline const ::idtxcore::Vector3& SeparateTransform::translation() const {
  // @@protoc_insertion_point(field_get:idtxcore.SeparateTransform.translation)
  return _internal_translation();
}
inline void SeparateTransform::unsafe_arena_set_allocated_translation(
    ::idtxcore::Vector3* translation) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.translation_);
  }
  _impl_.translation_ = translation;
  if (translation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.SeparateTransform.translation)
}
inline ::idtxcore::Vector3* SeparateTransform::release_translation() {
  
  ::idtxcore::Vector3* temp = _impl_.translation_;
  _impl_.translation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::idtxcore::Vector3* SeparateTransform::unsafe_arena_release_translation() {
  // @@protoc_insertion_point(field_release:idtxcore.SeparateTransform.translation)
  
  ::idtxcore::Vector3* temp = _impl_.translation_;
  _impl_.translation_ = nullptr;
  return temp;
}
inline ::idtxcore::Vector3* SeparateTransform::_internal_mutable_translation() {
  
  if (_impl_.translation_ == nullptr) {
    auto* p = CreateMaybeMessage<::idtxcore::Vector3>(GetArenaForAllocation());
    _impl_.translation_ = p;
  }
  return _impl_.translation_;
}
inline ::idtxcore::Vector3* SeparateTransform::mutable_translation() {
  ::idtxcore::Vector3* _msg = _internal_mutable_translation();
  // @@protoc_insertion_point(field_mutable:idtxcore.SeparateTransform.translation)
  return _msg;
}
inline void SeparateTransform::set_allocated_translation(::idtxcore::Vector3* translation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.translation_;
  }
  if (translation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(translation);
    if (message_arena != submessage_arena) {
      translation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, translation, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.translation_ = translation;
  // @@protoc_insertion_point(field_set_allocated:idtxcore.SeparateTransform.translation)
}

// .idtxcore.Vector3 rotation = 2;
inline bool SeparateTransform::_internal_has_rotation() const {
  return this != internal_default_instance() && _impl_.rotation_ != nullptr;
}
inline bool SeparateTransform::has_rotation() const {
  return _internal_has_rotation();
}
inline void SeparateTransform::clear_rotation() {
  if (GetArenaForAllocation() == nullptr && _impl_.rotation_ != nullptr) {
    delete _impl_.rotation_;
  }
  _impl_.rotation_ = nullptr;
}
inline const ::idtxcore::Vector3& SeparateTransform::_internal_rotation() const {
  const ::idtxcore::Vector3* p = _impl_.rotation_;
  return p != nullptr ? *p : reinterpret_cast<const ::idtxcore::Vector3&>(
      ::idtxcore::_Vector3_default_instance_);
}
inline const ::idtxcore::Vector3& SeparateTransform::rotation() const {
  // @@protoc_insertion_point(field_get:idtxcore.SeparateTransform.rotation)
  return _internal_rotation();
}
inline void SeparateTransform::unsafe_arena_set_allocated_rotation(
    ::idtxcore::Vector3* rotation) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rotation_);
  }
  _impl_.rotation_ = rotation;
  if (rotation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.SeparateTransform.rotation)
}
inline ::idtxcore::Vector3* SeparateTransform::release_rotation() {
  
  ::idtxcore::Vector3* temp = _impl_.rotation_;
  _impl_.rotation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::idtxcore::Vector3* SeparateTransform::unsafe_arena_release_rotation() {
  // @@protoc_insertion_point(field_release:idtxcore.SeparateTransform.rotation)
  
  ::idtxcore::Vector3* temp = _impl_.rotation_;
  _impl_.rotation_ = nullptr;
  return temp;
}
inline ::idtxcore::Vector3* SeparateTransform::_internal_mutable_rotation() {
  
  if (_impl_.rotation_ == nullptr) {
    auto* p = CreateMaybeMessage<::idtxcore::Vector3>(GetArenaForAllocation());
    _impl_.rotation_ = p;
  }
  return _impl_.rotation_;
}
inline ::idtxcore::Vector3* SeparateTransform::mutable_rotation() {
  ::idtxcore::Vector3* _msg = _internal_mutable_rotation();
  // @@protoc_insertion_point(field_mutable:idtxcore.SeparateTransform.rotation)
  return _msg;
}
inline void SeparateTransform::set_allocated_rotation(::idtxcore::Vector3* rotation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.rotation_;
  }
  if (rotation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(rotation);
    if (message_arena != submessage_arena) {
      rotation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rotation, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.rotation_ = rotation;
  // @@protoc_insertion_point(field_set_allocated:idtxcore.SeparateTransform.rotation)
}

// .idtxcore.Vector3 scale = 3;
inline bool SeparateTransform::_internal_has_scale() const {
  return this != internal_default_instance() && _impl_.scale_ != nullptr;
}
inline bool SeparateTransform::has_scale() const {
  return _internal_has_scale();
}
inline void SeparateTransform::clear_scale() {
  if (GetArenaForAllocation() == nullptr && _impl_.scale_ != nullptr) {
    delete _impl_.scale_;
  }
  _impl_.scale_ = nullptr;
}
inline const ::idtxcore::Vector3& SeparateTransform::_internal_scale() const {
  const ::idtxcore::Vector3* p = _impl_.scale_;
  return p != nullptr ? *p : reinterpret_cast<const ::idtxcore::Vector3&>(
      ::idtxcore::_Vector3_default_instance_);
}
inline const ::idtxcore::Vector3& SeparateTransform::scale() const {
  // @@protoc_insertion_point(field_get:idtxcore.SeparateTransform.scale)
  return _internal_scale();
}
inline void SeparateTransform::unsafe_arena_set_allocated_scale(
    ::idtxcore::Vector3* scale) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.scale_);
  }
  _impl_.scale_ = scale;
  if (scale) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.SeparateTransform.scale)
}
inline ::idtxcore::Vector3* SeparateTransform::release_scale() {
  
  ::idtxcore::Vector3* temp = _impl_.scale_;
  _impl_.scale_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::idtxcore::Vector3* SeparateTransform::unsafe_arena_release_scale() {
  // @@protoc_insertion_point(field_release:idtxcore.SeparateTransform.scale)
  
  ::idtxcore::Vector3* temp = _impl_.scale_;
  _impl_.scale_ = nullptr;
  return temp;
}
inline ::idtxcore::Vector3* SeparateTransform::_internal_mutable_scale() {
  
  if (_impl_.scale_ == nullptr) {
    auto* p = CreateMaybeMessage<::idtxcore::Vector3>(GetArenaForAllocation());
    _impl_.scale_ = p;
  }
  return _impl_.scale_;
}
inline ::idtxcore::Vector3* SeparateTransform::mutable_scale() {
  ::idtxcore::Vector3* _msg = _internal_mutable_scale();
  // @@protoc_insertion_point(field_mutable:idtxcore.SeparateTransform.scale)
  return _msg;
}
inline void SeparateTransform::set_allocated_scale(::idtxcore::Vector3* scale) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.scale_;
  }
  if (scale) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(scale);
    if (message_arena != submessage_arena) {
      scale = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, scale, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.scale_ = scale;
  // @@protoc_insertion_point(field_set_allocated:idtxcore.SeparateTransform.scale)
}

// -------------------------------------------------------------------

// TransformUpdate

// string session_id = 1;
inline void TransformUpdate::clear_session_id() {
  _impl_.session_id_.ClearToEmpty();
}
inline const std::string& TransformUpdate::session_id() const {
  // @@protoc_insertion_point(field_get:idtxcore.TransformUpdate.session_id)
  return _internal_session_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TransformUpdate::set_session_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.session_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:idtxcore.TransformUpdate.session_id)
}
inline std::string* TransformUpdate::mutable_session_id() {
  std::string* _s = _internal_mutable_session_id();
  // @@protoc_insertion_point(field_mutable:idtxcore.TransformUpdate.session_id)
  return _s;
}
inline const std::string& TransformUpdate::_internal_session_id() const {
  return _impl_.session_id_.Get();
}
inline void TransformUpdate::_internal_set_session_id(const std::string& value) {
  
  _impl_.session_id_.Set(value, GetArenaForAllocation());
}
inline std::string* TransformUpdate::_internal_mutable_session_id() {
  
  return _impl_.session_id_.Mutable(GetArenaForAllocation());
}
inline std::string* TransformUpdate::release_session_id() {
  // @@protoc_insertion_point(field_release:idtxcore.TransformUpdate.session_id)
  return _impl_.session_id_.Release();
}
inline void TransformUpdate::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    
  } else {
    
  }
  _impl_.session_id_.SetAllocated(session_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:idtxcore.TransformUpdate.session_id)
}

// string usd_file = 2;
inline void TransformUpdate::clear_usd_file() {
  _impl_.usd_file_.ClearToEmpty();
}
inline const std::string& TransformUpdate::usd_file() const {
  // @@protoc_insertion_point(field_get:idtxcore.TransformUpdate.usd_file)
  return _internal_usd_file();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TransformUpdate::set_usd_file(ArgT0&& arg0, ArgT... args) {
 
 _impl_.usd_file_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:idtxcore.TransformUpdate.usd_file)
}
inline std::string* TransformUpdate::mutable_usd_file() {
  std::string* _s = _internal_mutable_usd_file();
  // @@protoc_insertion_point(field_mutable:idtxcore.TransformUpdate.usd_file)
  return _s;
}
inline const std::string& TransformUpdate::_internal_usd_file() const {
  return _impl_.usd_file_.Get();
}
inline void TransformUpdate::_internal_set_usd_file(const std::string& value) {
  
  _impl_.usd_file_.Set(value, GetArenaForAllocation());
}
inline std::string* TransformUpdate::_internal_mutable_usd_file() {
  
  return _impl_.usd_file_.Mutable(GetArenaForAllocation());
}
inline std::string* TransformUpdate::release_usd_file() {
  // @@protoc_insertion_point(field_release:idtxcore.TransformUpdate.usd_file)
  return _impl_.usd_file_.Release();
}
inline void TransformUpdate::set_allocated_usd_file(std::string* usd_file) {
  if (usd_file != nullptr) {
    
  } else {
    
  }
  _impl_.usd_file_.SetAllocated(usd_file, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.usd_file_.IsDefault()) {
    _impl_.usd_file_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:idtxcore.TransformUpdate.usd_file)
}

// string prim_path = 3;
inline void TransformUpdate::clear_prim_path() {
  _impl_.prim_path_.ClearToEmpty();
}
inline const std::string& TransformUpdate::prim_path() const {
  // @@protoc_insertion_point(field_get:idtxcore.TransformUpdate.prim_path)
  return _internal_prim_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TransformUpdate::set_prim_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.prim_path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:idtxcore.TransformUpdate.prim_path)
}
inline std::string* TransformUpdate::mutable_prim_path() {
  std::string* _s = _internal_mutable_prim_path();
  // @@protoc_insertion_point(field_mutable:idtxcore.TransformUpdate.prim_path)
  return _s;
}
inline const std::string& TransformUpdate::_internal_prim_path() const {
  return _impl_.prim_path_.Get();
}
inline void TransformUpdate::_internal_set_prim_path(const std::string& value) {
  
  _impl_.prim_path_.Set(value, GetArenaForAllocation());
}
inline std::string* TransformUpdate::_internal_mutable_prim_path() {
  
  return _impl_.prim_path_.Mutable(GetArenaForAllocation());
}
inline std::string* TransformUpdate::release_prim_path() {
  // @@protoc_insertion_point(field_release:idtxcore.TransformUpdate.prim_path)
  return _impl_.prim_path_.Release();
}
inline void TransformUpdate::set_allocated_prim_path(std::string* prim_path) {
  if (prim_path != nullptr) {
    
  } else {
    
  }
  _impl_.prim_path_.SetAllocated(prim_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.prim_path_.IsDefault()) {
    _impl_.prim_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:idtxcore.TransformUpdate.prim_path)
}

// .idtxcore.SeparateTransform seperate = 4;
inline bool TransformUpdate::_internal_has_seperate() const {
  return transform_case() == kSeperate;
}
inline bool TransformUpdate::has_seperate() const {
  return _internal_has_seperate();
}
inline void TransformUpdate::set_has_seperate() {
  _impl_._oneof_case_[0] = kSeperate;
}
inline void TransformUpdate::clear_seperate() {
  if (_internal_has_seperate()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.transform_.seperate_;
    }
    clear_has_transform();
  }
}
inline ::idtxcore::SeparateTransform* TransformUpdate::release_seperate() {
  // @@protoc_insertion_point(field_release:idtxcore.TransformUpdate.seperate)
  if (_internal_has_seperate()) {
    clear_has_transform();
    ::idtxcore::SeparateTransform* temp = _impl_.transform_.seperate_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.transform_.seperate_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::SeparateTransform& TransformUpdate::_internal_seperate() const {
  return _internal_has_seperate()
      ? *_impl_.transform_.seperate_
      : reinterpret_cast< ::idtxcore::SeparateTransform&>(::idtxcore::_SeparateTransform_default_instance_);
}
inline const ::idtxcore::SeparateTransform& TransformUpdate::seperate() const {
  // @@protoc_insertion_point(field_get:idtxcore.TransformUpdate.seperate)
  return _internal_seperate();
}
inline ::idtxcore::SeparateTransform* TransformUpdate::unsafe_arena_release_seperate() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.TransformUpdate.seperate)
  if (_internal_has_seperate()) {
    clear_has_transform();
    ::idtxcore::SeparateTransform* temp = _impl_.transform_.seperate_;
    _impl_.transform_.seperate_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void TransformUpdate::unsafe_arena_set_allocated_seperate(::idtxcore::SeparateTransform* seperate) {
  clear_transform();
  if (seperate) {
    set_has_seperate();
    _impl_.transform_.seperate_ = seperate;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.TransformUpdate.seperate)
}
inline ::idtxcore::SeparateTransform* TransformUpdate::_internal_mutable_seperate() {
  if (!_internal_has_seperate()) {
    clear_transform();
    set_has_seperate();
    _impl_.transform_.seperate_ = CreateMaybeMessage< ::idtxcore::SeparateTransform >(GetArenaForAllocation());
  }
  return _impl_.transform_.seperate_;
}
inline ::idtxcore::SeparateTransform* TransformUpdate::mutable_seperate() {
  ::idtxcore::SeparateTransform* _msg = _internal_mutable_seperate();
  // @@protoc_insertion_point(field_mutable:idtxcore.TransformUpdate.seperate)
  return _msg;
}

// .idtxcore.Matrix4dTransform matrix = 5;
inline bool TransformUpdate::_internal_has_matrix() const {
  return transform_case() == kMatrix;
}
inline bool TransformUpdate::has_matrix() const {
  return _internal_has_matrix();
}
inline void TransformUpdate::set_has_matrix() {
  _impl_._oneof_case_[0] = kMatrix;
}
inline void TransformUpdate::clear_matrix() {
  if (_internal_has_matrix()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.transform_.matrix_;
    }
    clear_has_transform();
  }
}
inline ::idtxcore::Matrix4dTransform* TransformUpdate::release_matrix() {
  // @@protoc_insertion_point(field_release:idtxcore.TransformUpdate.matrix)
  if (_internal_has_matrix()) {
    clear_has_transform();
    ::idtxcore::Matrix4dTransform* temp = _impl_.transform_.matrix_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.transform_.matrix_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::Matrix4dTransform& TransformUpdate::_internal_matrix() const {
  return _internal_has_matrix()
      ? *_impl_.transform_.matrix_
      : reinterpret_cast< ::idtxcore::Matrix4dTransform&>(::idtxcore::_Matrix4dTransform_default_instance_);
}
inline const ::idtxcore::Matrix4dTransform& TransformUpdate::matrix() const {
  // @@protoc_insertion_point(field_get:idtxcore.TransformUpdate.matrix)
  return _internal_matrix();
}
inline ::idtxcore::Matrix4dTransform* TransformUpdate::unsafe_arena_release_matrix() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.TransformUpdate.matrix)
  if (_internal_has_matrix()) {
    clear_has_transform();
    ::idtxcore::Matrix4dTransform* temp = _impl_.transform_.matrix_;
    _impl_.transform_.matrix_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void TransformUpdate::unsafe_arena_set_allocated_matrix(::idtxcore::Matrix4dTransform* matrix) {
  clear_transform();
  if (matrix) {
    set_has_matrix();
    _impl_.transform_.matrix_ = matrix;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.TransformUpdate.matrix)
}
inline ::idtxcore::Matrix4dTransform* TransformUpdate::_internal_mutable_matrix() {
  if (!_internal_has_matrix()) {
    clear_transform();
    set_has_matrix();
    _impl_.transform_.matrix_ = CreateMaybeMessage< ::idtxcore::Matrix4dTransform >(GetArenaForAllocation());
  }
  return _impl_.transform_.matrix_;
}
inline ::idtxcore::Matrix4dTransform* TransformUpdate::mutable_matrix() {
  ::idtxcore::Matrix4dTransform* _msg = _internal_mutable_matrix();
  // @@protoc_insertion_point(field_mutable:idtxcore.TransformUpdate.matrix)
  return _msg;
}

// int64 timestamp = 7;
inline void TransformUpdate::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t TransformUpdate::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t TransformUpdate::timestamp() const {
  // @@protoc_insertion_point(field_get:idtxcore.TransformUpdate.timestamp)
  return _internal_timestamp();
}
inline void TransformUpdate::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void TransformUpdate::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:idtxcore.TransformUpdate.timestamp)
}

inline bool TransformUpdate::has_transform() const {
  return transform_case() != TRANSFORM_NOT_SET;
}
inline void TransformUpdate::clear_has_transform() {
  _impl_._oneof_case_[0] = TRANSFORM_NOT_SET;
}
inline TransformUpdate::TransformCase TransformUpdate::transform_case() const {
  return TransformUpdate::TransformCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// TransformBroadcast

// string client_id = 1;
inline void TransformBroadcast::clear_client_id() {
  _impl_.client_id_.ClearToEmpty();
}
inline const std::string& TransformBroadcast::client_id() const {
  // @@protoc_insertion_point(field_get:idtxcore.TransformBroadcast.client_id)
  return _internal_client_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TransformBroadcast::set_client_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.client_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:idtxcore.TransformBroadcast.client_id)
}
inline std::string* TransformBroadcast::mutable_client_id() {
  std::string* _s = _internal_mutable_client_id();
  // @@protoc_insertion_point(field_mutable:idtxcore.TransformBroadcast.client_id)
  return _s;
}
inline const std::string& TransformBroadcast::_internal_client_id() const {
  return _impl_.client_id_.Get();
}
inline void TransformBroadcast::_internal_set_client_id(const std::string& value) {
  
  _impl_.client_id_.Set(value, GetArenaForAllocation());
}
inline std::string* TransformBroadcast::_internal_mutable_client_id() {
  
  return _impl_.client_id_.Mutable(GetArenaForAllocation());
}
inline std::string* TransformBroadcast::release_client_id() {
  // @@protoc_insertion_point(field_release:idtxcore.TransformBroadcast.client_id)
  return _impl_.client_id_.Release();
}
inline void TransformBroadcast::set_allocated_client_id(std::string* client_id) {
  if (client_id != nullptr) {
    
  } else {
    
  }
  _impl_.client_id_.SetAllocated(client_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.client_id_.IsDefault()) {
    _impl_.client_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:idtxcore.TransformBroadcast.client_id)
}

// .idtxcore.TransformUpdate update = 2;
inline bool TransformBroadcast::_internal_has_update() const {
  return this != internal_default_instance() && _impl_.update_ != nullptr;
}
inline bool TransformBroadcast::has_update() const {
  return _internal_has_update();
}
inline void TransformBroadcast::clear_update() {
  if (GetArenaForAllocation() == nullptr && _impl_.update_ != nullptr) {
    delete _impl_.update_;
  }
  _impl_.update_ = nullptr;
}
inline const ::idtxcore::TransformUpdate& TransformBroadcast::_internal_update() const {
  const ::idtxcore::TransformUpdate* p = _impl_.update_;
  return p != nullptr ? *p : reinterpret_cast<const ::idtxcore::TransformUpdate&>(
      ::idtxcore::_TransformUpdate_default_instance_);
}
inline const ::idtxcore::TransformUpdate& TransformBroadcast::update() const {
  // @@protoc_insertion_point(field_get:idtxcore.TransformBroadcast.update)
  return _internal_update();
}
inline void TransformBroadcast::unsafe_arena_set_allocated_update(
    ::idtxcore::TransformUpdate* update) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.update_);
  }
  _impl_.update_ = update;
  if (update) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.TransformBroadcast.update)
}
inline ::idtxcore::TransformUpdate* TransformBroadcast::release_update() {
  
  ::idtxcore::TransformUpdate* temp = _impl_.update_;
  _impl_.update_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::idtxcore::TransformUpdate* TransformBroadcast::unsafe_arena_release_update() {
  // @@protoc_insertion_point(field_release:idtxcore.TransformBroadcast.update)
  
  ::idtxcore::TransformUpdate* temp = _impl_.update_;
  _impl_.update_ = nullptr;
  return temp;
}
inline ::idtxcore::TransformUpdate* TransformBroadcast::_internal_mutable_update() {
  
  if (_impl_.update_ == nullptr) {
    auto* p = CreateMaybeMessage<::idtxcore::TransformUpdate>(GetArenaForAllocation());
    _impl_.update_ = p;
  }
  return _impl_.update_;
}
inline ::idtxcore::TransformUpdate* TransformBroadcast::mutable_update() {
  ::idtxcore::TransformUpdate* _msg = _internal_mutable_update();
  // @@protoc_insertion_point(field_mutable:idtxcore.TransformBroadcast.update)
  return _msg;
}
inline void TransformBroadcast::set_allocated_update(::idtxcore::TransformUpdate* update) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.update_;
  }
  if (update) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(update);
    if (message_arena != submessage_arena) {
      update = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, update, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.update_ = update;
  // @@protoc_insertion_point(field_set_allocated:idtxcore.TransformBroadcast.update)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace idtxcore

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_transform_2eproto
