// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transform.proto

#include "transform.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace idtxcore {
PROTOBUF_CONSTEXPR Vector3::Vector3(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.z_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Vector3DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Vector3DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Vector3DefaultTypeInternal() {}
  union {
    Vector3 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Vector3DefaultTypeInternal _Vector3_default_instance_;
PROTOBUF_CONSTEXPR Matrix4dTransform::Matrix4dTransform(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.m00_)*/0
  , /*decltype(_impl_.m01_)*/0
  , /*decltype(_impl_.m02_)*/0
  , /*decltype(_impl_.m03_)*/0
  , /*decltype(_impl_.m10_)*/0
  , /*decltype(_impl_.m11_)*/0
  , /*decltype(_impl_.m12_)*/0
  , /*decltype(_impl_.m13_)*/0
  , /*decltype(_impl_.m20_)*/0
  , /*decltype(_impl_.m21_)*/0
  , /*decltype(_impl_.m22_)*/0
  , /*decltype(_impl_.m23_)*/0
  , /*decltype(_impl_.m30_)*/0
  , /*decltype(_impl_.m31_)*/0
  , /*decltype(_impl_.m32_)*/0
  , /*decltype(_impl_.m33_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Matrix4dTransformDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Matrix4dTransformDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Matrix4dTransformDefaultTypeInternal() {}
  union {
    Matrix4dTransform _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Matrix4dTransformDefaultTypeInternal _Matrix4dTransform_default_instance_;
PROTOBUF_CONSTEXPR SeparateTransform::SeparateTransform(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.translation_)*/nullptr
  , /*decltype(_impl_.rotation_)*/nullptr
  , /*decltype(_impl_.scale_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SeparateTransformDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SeparateTransformDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SeparateTransformDefaultTypeInternal() {}
  union {
    SeparateTransform _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SeparateTransformDefaultTypeInternal _SeparateTransform_default_instance_;
PROTOBUF_CONSTEXPR TransformUpdate::TransformUpdate(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.session_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.usd_file_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.prim_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_.transform_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct TransformUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransformUpdateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransformUpdateDefaultTypeInternal() {}
  union {
    TransformUpdate _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransformUpdateDefaultTypeInternal _TransformUpdate_default_instance_;
PROTOBUF_CONSTEXPR TransformBroadcast::TransformBroadcast(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.client_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.update_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TransformBroadcastDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransformBroadcastDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransformBroadcastDefaultTypeInternal() {}
  union {
    TransformBroadcast _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransformBroadcastDefaultTypeInternal _TransformBroadcast_default_instance_;
}  // namespace idtxcore
static ::_pb::Metadata file_level_metadata_transform_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_transform_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_transform_2eproto = nullptr;

const uint32_t TableStruct_transform_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::idtxcore::Vector3, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::idtxcore::Vector3, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Vector3, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Vector3, _impl_.z_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m00_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m01_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m02_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m03_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m10_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m11_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m12_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m13_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m20_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m21_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m22_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m23_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m30_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m31_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m32_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::Matrix4dTransform, _impl_.m33_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::idtxcore::SeparateTransform, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::idtxcore::SeparateTransform, _impl_.translation_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::SeparateTransform, _impl_.rotation_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::SeparateTransform, _impl_.scale_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::idtxcore::TransformUpdate, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::idtxcore::TransformUpdate, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::idtxcore::TransformUpdate, _impl_.session_id_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::TransformUpdate, _impl_.usd_file_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::TransformUpdate, _impl_.prim_path_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::idtxcore::TransformUpdate, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::TransformUpdate, _impl_.transform_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::idtxcore::TransformBroadcast, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::idtxcore::TransformBroadcast, _impl_.client_id_),
  PROTOBUF_FIELD_OFFSET(::idtxcore::TransformBroadcast, _impl_.update_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::idtxcore::Vector3)},
  { 9, -1, -1, sizeof(::idtxcore::Matrix4dTransform)},
  { 31, -1, -1, sizeof(::idtxcore::SeparateTransform)},
  { 40, -1, -1, sizeof(::idtxcore::TransformUpdate)},
  { 53, -1, -1, sizeof(::idtxcore::TransformBroadcast)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::idtxcore::_Vector3_default_instance_._instance,
  &::idtxcore::_Matrix4dTransform_default_instance_._instance,
  &::idtxcore::_SeparateTransform_default_instance_._instance,
  &::idtxcore::_TransformUpdate_default_instance_._instance,
  &::idtxcore::_TransformBroadcast_default_instance_._instance,
};

const char descriptor_table_protodef_transform_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017transform.proto\022\010idtxcore\"*\n\007Vector3\022\t"
  "\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\t\n\001z\030\003 \001(\001\"\343\001\n\021Matr"
  "ix4dTransform\022\013\n\003m00\030\001 \001(\001\022\013\n\003m01\030\002 \001(\001\022"
  "\013\n\003m02\030\003 \001(\001\022\013\n\003m03\030\004 \001(\001\022\013\n\003m10\030\005 \001(\001\022\013"
  "\n\003m11\030\006 \001(\001\022\013\n\003m12\030\007 \001(\001\022\013\n\003m13\030\010 \001(\001\022\013\n"
  "\003m20\030\t \001(\001\022\013\n\003m21\030\n \001(\001\022\013\n\003m22\030\013 \001(\001\022\013\n\003"
  "m23\030\014 \001(\001\022\013\n\003m30\030\r \001(\001\022\013\n\003m31\030\016 \001(\001\022\013\n\003m"
  "32\030\017 \001(\001\022\013\n\003m33\030\020 \001(\001\"\202\001\n\021SeparateTransf"
  "orm\022&\n\013translation\030\001 \001(\0132\021.idtxcore.Vect"
  "or3\022#\n\010rotation\030\002 \001(\0132\021.idtxcore.Vector3"
  "\022 \n\005scale\030\003 \001(\0132\021.idtxcore.Vector3\"\312\001\n\017T"
  "ransformUpdate\022\022\n\nsession_id\030\001 \001(\t\022\020\n\010us"
  "d_file\030\002 \001(\t\022\021\n\tprim_path\030\003 \001(\t\022/\n\010seper"
  "ate\030\004 \001(\0132\033.idtxcore.SeparateTransformH\000"
  "\022-\n\006matrix\030\005 \001(\0132\033.idtxcore.Matrix4dTran"
  "sformH\000\022\021\n\ttimestamp\030\007 \001(\003B\013\n\ttransform\""
  "R\n\022TransformBroadcast\022\021\n\tclient_id\030\001 \001(\t"
  "\022)\n\006update\030\002 \001(\0132\031.idtxcore.TransformUpd"
  "ateb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_transform_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_transform_2eproto = {
    false, false, 731, descriptor_table_protodef_transform_2eproto,
    "transform.proto",
    &descriptor_table_transform_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_transform_2eproto::offsets,
    file_level_metadata_transform_2eproto, file_level_enum_descriptors_transform_2eproto,
    file_level_service_descriptors_transform_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_transform_2eproto_getter() {
  return &descriptor_table_transform_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_transform_2eproto(&descriptor_table_transform_2eproto);
namespace idtxcore {

// ===================================================================

class Vector3::_Internal {
 public:
};

Vector3::Vector3(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:idtxcore.Vector3)
}
Vector3::Vector3(const Vector3& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Vector3* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.z_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.z_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  // @@protoc_insertion_point(copy_constructor:idtxcore.Vector3)
}

inline void Vector3::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.z_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Vector3::~Vector3() {
  // @@protoc_insertion_point(destructor:idtxcore.Vector3)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Vector3::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Vector3::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Vector3::Clear() {
// @@protoc_insertion_point(message_clear_start:idtxcore.Vector3)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Vector3::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Vector3::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:idtxcore.Vector3)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_x(), target);
  }

  // double y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_y(), target);
  }

  // double z = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_z = this->_internal_z();
  uint64_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:idtxcore.Vector3)
  return target;
}

size_t Vector3::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:idtxcore.Vector3)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 8;
  }

  // double y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 8;
  }

  // double z = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_z = this->_internal_z();
  uint64_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Vector3::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Vector3::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Vector3::GetClassData() const { return &_class_data_; }


void Vector3::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Vector3*>(&to_msg);
  auto& from = static_cast<const Vector3&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:idtxcore.Vector3)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = from._internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = from._internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_z = from._internal_z();
  uint64_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Vector3::CopyFrom(const Vector3& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:idtxcore.Vector3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vector3::IsInitialized() const {
  return true;
}

void Vector3::InternalSwap(Vector3* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Vector3, _impl_.z_)
      + sizeof(Vector3::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(Vector3, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Vector3::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_transform_2eproto_getter, &descriptor_table_transform_2eproto_once,
      file_level_metadata_transform_2eproto[0]);
}

// ===================================================================

class Matrix4dTransform::_Internal {
 public:
};

Matrix4dTransform::Matrix4dTransform(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:idtxcore.Matrix4dTransform)
}
Matrix4dTransform::Matrix4dTransform(const Matrix4dTransform& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Matrix4dTransform* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.m00_){}
    , decltype(_impl_.m01_){}
    , decltype(_impl_.m02_){}
    , decltype(_impl_.m03_){}
    , decltype(_impl_.m10_){}
    , decltype(_impl_.m11_){}
    , decltype(_impl_.m12_){}
    , decltype(_impl_.m13_){}
    , decltype(_impl_.m20_){}
    , decltype(_impl_.m21_){}
    , decltype(_impl_.m22_){}
    , decltype(_impl_.m23_){}
    , decltype(_impl_.m30_){}
    , decltype(_impl_.m31_){}
    , decltype(_impl_.m32_){}
    , decltype(_impl_.m33_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.m00_, &from._impl_.m00_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.m33_) -
    reinterpret_cast<char*>(&_impl_.m00_)) + sizeof(_impl_.m33_));
  // @@protoc_insertion_point(copy_constructor:idtxcore.Matrix4dTransform)
}

inline void Matrix4dTransform::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.m00_){0}
    , decltype(_impl_.m01_){0}
    , decltype(_impl_.m02_){0}
    , decltype(_impl_.m03_){0}
    , decltype(_impl_.m10_){0}
    , decltype(_impl_.m11_){0}
    , decltype(_impl_.m12_){0}
    , decltype(_impl_.m13_){0}
    , decltype(_impl_.m20_){0}
    , decltype(_impl_.m21_){0}
    , decltype(_impl_.m22_){0}
    , decltype(_impl_.m23_){0}
    , decltype(_impl_.m30_){0}
    , decltype(_impl_.m31_){0}
    , decltype(_impl_.m32_){0}
    , decltype(_impl_.m33_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Matrix4dTransform::~Matrix4dTransform() {
  // @@protoc_insertion_point(destructor:idtxcore.Matrix4dTransform)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Matrix4dTransform::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Matrix4dTransform::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Matrix4dTransform::Clear() {
// @@protoc_insertion_point(message_clear_start:idtxcore.Matrix4dTransform)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.m00_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.m33_) -
      reinterpret_cast<char*>(&_impl_.m00_)) + sizeof(_impl_.m33_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Matrix4dTransform::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double m00 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.m00_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m01 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.m01_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m02 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.m02_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m03 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.m03_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m10 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.m10_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m11 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.m11_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m12 = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _impl_.m12_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m13 = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 65)) {
          _impl_.m13_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m20 = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 73)) {
          _impl_.m20_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m21 = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 81)) {
          _impl_.m21_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m22 = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 89)) {
          _impl_.m22_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m23 = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 97)) {
          _impl_.m23_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m30 = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 105)) {
          _impl_.m30_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m31 = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 113)) {
          _impl_.m31_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m32 = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 121)) {
          _impl_.m32_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double m33 = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 129)) {
          _impl_.m33_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Matrix4dTransform::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:idtxcore.Matrix4dTransform)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double m00 = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m00 = this->_internal_m00();
  uint64_t raw_m00;
  memcpy(&raw_m00, &tmp_m00, sizeof(tmp_m00));
  if (raw_m00 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_m00(), target);
  }

  // double m01 = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m01 = this->_internal_m01();
  uint64_t raw_m01;
  memcpy(&raw_m01, &tmp_m01, sizeof(tmp_m01));
  if (raw_m01 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_m01(), target);
  }

  // double m02 = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m02 = this->_internal_m02();
  uint64_t raw_m02;
  memcpy(&raw_m02, &tmp_m02, sizeof(tmp_m02));
  if (raw_m02 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_m02(), target);
  }

  // double m03 = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m03 = this->_internal_m03();
  uint64_t raw_m03;
  memcpy(&raw_m03, &tmp_m03, sizeof(tmp_m03));
  if (raw_m03 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_m03(), target);
  }

  // double m10 = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m10 = this->_internal_m10();
  uint64_t raw_m10;
  memcpy(&raw_m10, &tmp_m10, sizeof(tmp_m10));
  if (raw_m10 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_m10(), target);
  }

  // double m11 = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m11 = this->_internal_m11();
  uint64_t raw_m11;
  memcpy(&raw_m11, &tmp_m11, sizeof(tmp_m11));
  if (raw_m11 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_m11(), target);
  }

  // double m12 = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m12 = this->_internal_m12();
  uint64_t raw_m12;
  memcpy(&raw_m12, &tmp_m12, sizeof(tmp_m12));
  if (raw_m12 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_m12(), target);
  }

  // double m13 = 8;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m13 = this->_internal_m13();
  uint64_t raw_m13;
  memcpy(&raw_m13, &tmp_m13, sizeof(tmp_m13));
  if (raw_m13 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(8, this->_internal_m13(), target);
  }

  // double m20 = 9;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m20 = this->_internal_m20();
  uint64_t raw_m20;
  memcpy(&raw_m20, &tmp_m20, sizeof(tmp_m20));
  if (raw_m20 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(9, this->_internal_m20(), target);
  }

  // double m21 = 10;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m21 = this->_internal_m21();
  uint64_t raw_m21;
  memcpy(&raw_m21, &tmp_m21, sizeof(tmp_m21));
  if (raw_m21 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(10, this->_internal_m21(), target);
  }

  // double m22 = 11;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m22 = this->_internal_m22();
  uint64_t raw_m22;
  memcpy(&raw_m22, &tmp_m22, sizeof(tmp_m22));
  if (raw_m22 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(11, this->_internal_m22(), target);
  }

  // double m23 = 12;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m23 = this->_internal_m23();
  uint64_t raw_m23;
  memcpy(&raw_m23, &tmp_m23, sizeof(tmp_m23));
  if (raw_m23 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(12, this->_internal_m23(), target);
  }

  // double m30 = 13;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m30 = this->_internal_m30();
  uint64_t raw_m30;
  memcpy(&raw_m30, &tmp_m30, sizeof(tmp_m30));
  if (raw_m30 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(13, this->_internal_m30(), target);
  }

  // double m31 = 14;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m31 = this->_internal_m31();
  uint64_t raw_m31;
  memcpy(&raw_m31, &tmp_m31, sizeof(tmp_m31));
  if (raw_m31 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(14, this->_internal_m31(), target);
  }

  // double m32 = 15;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m32 = this->_internal_m32();
  uint64_t raw_m32;
  memcpy(&raw_m32, &tmp_m32, sizeof(tmp_m32));
  if (raw_m32 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(15, this->_internal_m32(), target);
  }

  // double m33 = 16;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m33 = this->_internal_m33();
  uint64_t raw_m33;
  memcpy(&raw_m33, &tmp_m33, sizeof(tmp_m33));
  if (raw_m33 != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(16, this->_internal_m33(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:idtxcore.Matrix4dTransform)
  return target;
}

size_t Matrix4dTransform::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:idtxcore.Matrix4dTransform)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double m00 = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m00 = this->_internal_m00();
  uint64_t raw_m00;
  memcpy(&raw_m00, &tmp_m00, sizeof(tmp_m00));
  if (raw_m00 != 0) {
    total_size += 1 + 8;
  }

  // double m01 = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m01 = this->_internal_m01();
  uint64_t raw_m01;
  memcpy(&raw_m01, &tmp_m01, sizeof(tmp_m01));
  if (raw_m01 != 0) {
    total_size += 1 + 8;
  }

  // double m02 = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m02 = this->_internal_m02();
  uint64_t raw_m02;
  memcpy(&raw_m02, &tmp_m02, sizeof(tmp_m02));
  if (raw_m02 != 0) {
    total_size += 1 + 8;
  }

  // double m03 = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m03 = this->_internal_m03();
  uint64_t raw_m03;
  memcpy(&raw_m03, &tmp_m03, sizeof(tmp_m03));
  if (raw_m03 != 0) {
    total_size += 1 + 8;
  }

  // double m10 = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m10 = this->_internal_m10();
  uint64_t raw_m10;
  memcpy(&raw_m10, &tmp_m10, sizeof(tmp_m10));
  if (raw_m10 != 0) {
    total_size += 1 + 8;
  }

  // double m11 = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m11 = this->_internal_m11();
  uint64_t raw_m11;
  memcpy(&raw_m11, &tmp_m11, sizeof(tmp_m11));
  if (raw_m11 != 0) {
    total_size += 1 + 8;
  }

  // double m12 = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m12 = this->_internal_m12();
  uint64_t raw_m12;
  memcpy(&raw_m12, &tmp_m12, sizeof(tmp_m12));
  if (raw_m12 != 0) {
    total_size += 1 + 8;
  }

  // double m13 = 8;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m13 = this->_internal_m13();
  uint64_t raw_m13;
  memcpy(&raw_m13, &tmp_m13, sizeof(tmp_m13));
  if (raw_m13 != 0) {
    total_size += 1 + 8;
  }

  // double m20 = 9;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m20 = this->_internal_m20();
  uint64_t raw_m20;
  memcpy(&raw_m20, &tmp_m20, sizeof(tmp_m20));
  if (raw_m20 != 0) {
    total_size += 1 + 8;
  }

  // double m21 = 10;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m21 = this->_internal_m21();
  uint64_t raw_m21;
  memcpy(&raw_m21, &tmp_m21, sizeof(tmp_m21));
  if (raw_m21 != 0) {
    total_size += 1 + 8;
  }

  // double m22 = 11;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m22 = this->_internal_m22();
  uint64_t raw_m22;
  memcpy(&raw_m22, &tmp_m22, sizeof(tmp_m22));
  if (raw_m22 != 0) {
    total_size += 1 + 8;
  }

  // double m23 = 12;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m23 = this->_internal_m23();
  uint64_t raw_m23;
  memcpy(&raw_m23, &tmp_m23, sizeof(tmp_m23));
  if (raw_m23 != 0) {
    total_size += 1 + 8;
  }

  // double m30 = 13;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m30 = this->_internal_m30();
  uint64_t raw_m30;
  memcpy(&raw_m30, &tmp_m30, sizeof(tmp_m30));
  if (raw_m30 != 0) {
    total_size += 1 + 8;
  }

  // double m31 = 14;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m31 = this->_internal_m31();
  uint64_t raw_m31;
  memcpy(&raw_m31, &tmp_m31, sizeof(tmp_m31));
  if (raw_m31 != 0) {
    total_size += 1 + 8;
  }

  // double m32 = 15;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m32 = this->_internal_m32();
  uint64_t raw_m32;
  memcpy(&raw_m32, &tmp_m32, sizeof(tmp_m32));
  if (raw_m32 != 0) {
    total_size += 1 + 8;
  }

  // double m33 = 16;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m33 = this->_internal_m33();
  uint64_t raw_m33;
  memcpy(&raw_m33, &tmp_m33, sizeof(tmp_m33));
  if (raw_m33 != 0) {
    total_size += 2 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Matrix4dTransform::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Matrix4dTransform::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Matrix4dTransform::GetClassData() const { return &_class_data_; }


void Matrix4dTransform::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Matrix4dTransform*>(&to_msg);
  auto& from = static_cast<const Matrix4dTransform&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:idtxcore.Matrix4dTransform)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m00 = from._internal_m00();
  uint64_t raw_m00;
  memcpy(&raw_m00, &tmp_m00, sizeof(tmp_m00));
  if (raw_m00 != 0) {
    _this->_internal_set_m00(from._internal_m00());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m01 = from._internal_m01();
  uint64_t raw_m01;
  memcpy(&raw_m01, &tmp_m01, sizeof(tmp_m01));
  if (raw_m01 != 0) {
    _this->_internal_set_m01(from._internal_m01());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m02 = from._internal_m02();
  uint64_t raw_m02;
  memcpy(&raw_m02, &tmp_m02, sizeof(tmp_m02));
  if (raw_m02 != 0) {
    _this->_internal_set_m02(from._internal_m02());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m03 = from._internal_m03();
  uint64_t raw_m03;
  memcpy(&raw_m03, &tmp_m03, sizeof(tmp_m03));
  if (raw_m03 != 0) {
    _this->_internal_set_m03(from._internal_m03());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m10 = from._internal_m10();
  uint64_t raw_m10;
  memcpy(&raw_m10, &tmp_m10, sizeof(tmp_m10));
  if (raw_m10 != 0) {
    _this->_internal_set_m10(from._internal_m10());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m11 = from._internal_m11();
  uint64_t raw_m11;
  memcpy(&raw_m11, &tmp_m11, sizeof(tmp_m11));
  if (raw_m11 != 0) {
    _this->_internal_set_m11(from._internal_m11());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m12 = from._internal_m12();
  uint64_t raw_m12;
  memcpy(&raw_m12, &tmp_m12, sizeof(tmp_m12));
  if (raw_m12 != 0) {
    _this->_internal_set_m12(from._internal_m12());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m13 = from._internal_m13();
  uint64_t raw_m13;
  memcpy(&raw_m13, &tmp_m13, sizeof(tmp_m13));
  if (raw_m13 != 0) {
    _this->_internal_set_m13(from._internal_m13());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m20 = from._internal_m20();
  uint64_t raw_m20;
  memcpy(&raw_m20, &tmp_m20, sizeof(tmp_m20));
  if (raw_m20 != 0) {
    _this->_internal_set_m20(from._internal_m20());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m21 = from._internal_m21();
  uint64_t raw_m21;
  memcpy(&raw_m21, &tmp_m21, sizeof(tmp_m21));
  if (raw_m21 != 0) {
    _this->_internal_set_m21(from._internal_m21());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m22 = from._internal_m22();
  uint64_t raw_m22;
  memcpy(&raw_m22, &tmp_m22, sizeof(tmp_m22));
  if (raw_m22 != 0) {
    _this->_internal_set_m22(from._internal_m22());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m23 = from._internal_m23();
  uint64_t raw_m23;
  memcpy(&raw_m23, &tmp_m23, sizeof(tmp_m23));
  if (raw_m23 != 0) {
    _this->_internal_set_m23(from._internal_m23());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m30 = from._internal_m30();
  uint64_t raw_m30;
  memcpy(&raw_m30, &tmp_m30, sizeof(tmp_m30));
  if (raw_m30 != 0) {
    _this->_internal_set_m30(from._internal_m30());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m31 = from._internal_m31();
  uint64_t raw_m31;
  memcpy(&raw_m31, &tmp_m31, sizeof(tmp_m31));
  if (raw_m31 != 0) {
    _this->_internal_set_m31(from._internal_m31());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m32 = from._internal_m32();
  uint64_t raw_m32;
  memcpy(&raw_m32, &tmp_m32, sizeof(tmp_m32));
  if (raw_m32 != 0) {
    _this->_internal_set_m32(from._internal_m32());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_m33 = from._internal_m33();
  uint64_t raw_m33;
  memcpy(&raw_m33, &tmp_m33, sizeof(tmp_m33));
  if (raw_m33 != 0) {
    _this->_internal_set_m33(from._internal_m33());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Matrix4dTransform::CopyFrom(const Matrix4dTransform& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:idtxcore.Matrix4dTransform)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Matrix4dTransform::IsInitialized() const {
  return true;
}

void Matrix4dTransform::InternalSwap(Matrix4dTransform* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Matrix4dTransform, _impl_.m33_)
      + sizeof(Matrix4dTransform::_impl_.m33_)
      - PROTOBUF_FIELD_OFFSET(Matrix4dTransform, _impl_.m00_)>(
          reinterpret_cast<char*>(&_impl_.m00_),
          reinterpret_cast<char*>(&other->_impl_.m00_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Matrix4dTransform::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_transform_2eproto_getter, &descriptor_table_transform_2eproto_once,
      file_level_metadata_transform_2eproto[1]);
}

// ===================================================================

class SeparateTransform::_Internal {
 public:
  static const ::idtxcore::Vector3& translation(const SeparateTransform* msg);
  static const ::idtxcore::Vector3& rotation(const SeparateTransform* msg);
  static const ::idtxcore::Vector3& scale(const SeparateTransform* msg);
};

const ::idtxcore::Vector3&
SeparateTransform::_Internal::translation(const SeparateTransform* msg) {
  return *msg->_impl_.translation_;
}
const ::idtxcore::Vector3&
SeparateTransform::_Internal::rotation(const SeparateTransform* msg) {
  return *msg->_impl_.rotation_;
}
const ::idtxcore::Vector3&
SeparateTransform::_Internal::scale(const SeparateTransform* msg) {
  return *msg->_impl_.scale_;
}
SeparateTransform::SeparateTransform(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:idtxcore.SeparateTransform)
}
SeparateTransform::SeparateTransform(const SeparateTransform& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SeparateTransform* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.translation_){nullptr}
    , decltype(_impl_.rotation_){nullptr}
    , decltype(_impl_.scale_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_translation()) {
    _this->_impl_.translation_ = new ::idtxcore::Vector3(*from._impl_.translation_);
  }
  if (from._internal_has_rotation()) {
    _this->_impl_.rotation_ = new ::idtxcore::Vector3(*from._impl_.rotation_);
  }
  if (from._internal_has_scale()) {
    _this->_impl_.scale_ = new ::idtxcore::Vector3(*from._impl_.scale_);
  }
  // @@protoc_insertion_point(copy_constructor:idtxcore.SeparateTransform)
}

inline void SeparateTransform::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.translation_){nullptr}
    , decltype(_impl_.rotation_){nullptr}
    , decltype(_impl_.scale_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SeparateTransform::~SeparateTransform() {
  // @@protoc_insertion_point(destructor:idtxcore.SeparateTransform)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SeparateTransform::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.translation_;
  if (this != internal_default_instance()) delete _impl_.rotation_;
  if (this != internal_default_instance()) delete _impl_.scale_;
}

void SeparateTransform::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SeparateTransform::Clear() {
// @@protoc_insertion_point(message_clear_start:idtxcore.SeparateTransform)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.translation_ != nullptr) {
    delete _impl_.translation_;
  }
  _impl_.translation_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.rotation_ != nullptr) {
    delete _impl_.rotation_;
  }
  _impl_.rotation_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.scale_ != nullptr) {
    delete _impl_.scale_;
  }
  _impl_.scale_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SeparateTransform::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .idtxcore.Vector3 translation = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_translation(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .idtxcore.Vector3 rotation = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_rotation(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .idtxcore.Vector3 scale = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_scale(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SeparateTransform::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:idtxcore.SeparateTransform)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .idtxcore.Vector3 translation = 1;
  if (this->_internal_has_translation()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::translation(this),
        _Internal::translation(this).GetCachedSize(), target, stream);
  }

  // .idtxcore.Vector3 rotation = 2;
  if (this->_internal_has_rotation()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::rotation(this),
        _Internal::rotation(this).GetCachedSize(), target, stream);
  }

  // .idtxcore.Vector3 scale = 3;
  if (this->_internal_has_scale()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::scale(this),
        _Internal::scale(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:idtxcore.SeparateTransform)
  return target;
}

size_t SeparateTransform::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:idtxcore.SeparateTransform)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .idtxcore.Vector3 translation = 1;
  if (this->_internal_has_translation()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.translation_);
  }

  // .idtxcore.Vector3 rotation = 2;
  if (this->_internal_has_rotation()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.rotation_);
  }

  // .idtxcore.Vector3 scale = 3;
  if (this->_internal_has_scale()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.scale_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SeparateTransform::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SeparateTransform::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SeparateTransform::GetClassData() const { return &_class_data_; }


void SeparateTransform::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SeparateTransform*>(&to_msg);
  auto& from = static_cast<const SeparateTransform&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:idtxcore.SeparateTransform)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_translation()) {
    _this->_internal_mutable_translation()->::idtxcore::Vector3::MergeFrom(
        from._internal_translation());
  }
  if (from._internal_has_rotation()) {
    _this->_internal_mutable_rotation()->::idtxcore::Vector3::MergeFrom(
        from._internal_rotation());
  }
  if (from._internal_has_scale()) {
    _this->_internal_mutable_scale()->::idtxcore::Vector3::MergeFrom(
        from._internal_scale());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SeparateTransform::CopyFrom(const SeparateTransform& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:idtxcore.SeparateTransform)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SeparateTransform::IsInitialized() const {
  return true;
}

void SeparateTransform::InternalSwap(SeparateTransform* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SeparateTransform, _impl_.scale_)
      + sizeof(SeparateTransform::_impl_.scale_)
      - PROTOBUF_FIELD_OFFSET(SeparateTransform, _impl_.translation_)>(
          reinterpret_cast<char*>(&_impl_.translation_),
          reinterpret_cast<char*>(&other->_impl_.translation_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SeparateTransform::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_transform_2eproto_getter, &descriptor_table_transform_2eproto_once,
      file_level_metadata_transform_2eproto[2]);
}

// ===================================================================

class TransformUpdate::_Internal {
 public:
  static const ::idtxcore::SeparateTransform& seperate(const TransformUpdate* msg);
  static const ::idtxcore::Matrix4dTransform& matrix(const TransformUpdate* msg);
};

const ::idtxcore::SeparateTransform&
TransformUpdate::_Internal::seperate(const TransformUpdate* msg) {
  return *msg->_impl_.transform_.seperate_;
}
const ::idtxcore::Matrix4dTransform&
TransformUpdate::_Internal::matrix(const TransformUpdate* msg) {
  return *msg->_impl_.transform_.matrix_;
}
void TransformUpdate::set_allocated_seperate(::idtxcore::SeparateTransform* seperate) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_transform();
  if (seperate) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(seperate);
    if (message_arena != submessage_arena) {
      seperate = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, seperate, submessage_arena);
    }
    set_has_seperate();
    _impl_.transform_.seperate_ = seperate;
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.TransformUpdate.seperate)
}
void TransformUpdate::set_allocated_matrix(::idtxcore::Matrix4dTransform* matrix) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_transform();
  if (matrix) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(matrix);
    if (message_arena != submessage_arena) {
      matrix = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, matrix, submessage_arena);
    }
    set_has_matrix();
    _impl_.transform_.matrix_ = matrix;
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.TransformUpdate.matrix)
}
TransformUpdate::TransformUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:idtxcore.TransformUpdate)
}
TransformUpdate::TransformUpdate(const TransformUpdate& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TransformUpdate* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.session_id_){}
    , decltype(_impl_.usd_file_){}
    , decltype(_impl_.prim_path_){}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.transform_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_session_id().empty()) {
    _this->_impl_.session_id_.Set(from._internal_session_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.usd_file_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.usd_file_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_usd_file().empty()) {
    _this->_impl_.usd_file_.Set(from._internal_usd_file(), 
      _this->GetArenaForAllocation());
  }
  _impl_.prim_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.prim_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_prim_path().empty()) {
    _this->_impl_.prim_path_.Set(from._internal_prim_path(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.timestamp_ = from._impl_.timestamp_;
  clear_has_transform();
  switch (from.transform_case()) {
    case kSeperate: {
      _this->_internal_mutable_seperate()->::idtxcore::SeparateTransform::MergeFrom(
          from._internal_seperate());
      break;
    }
    case kMatrix: {
      _this->_internal_mutable_matrix()->::idtxcore::Matrix4dTransform::MergeFrom(
          from._internal_matrix());
      break;
    }
    case TRANSFORM_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:idtxcore.TransformUpdate)
}

inline void TransformUpdate::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.session_id_){}
    , decltype(_impl_.usd_file_){}
    , decltype(_impl_.prim_path_){}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , decltype(_impl_.transform_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.usd_file_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.usd_file_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.prim_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.prim_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_transform();
}

TransformUpdate::~TransformUpdate() {
  // @@protoc_insertion_point(destructor:idtxcore.TransformUpdate)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TransformUpdate::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.session_id_.Destroy();
  _impl_.usd_file_.Destroy();
  _impl_.prim_path_.Destroy();
  if (has_transform()) {
    clear_transform();
  }
}

void TransformUpdate::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TransformUpdate::clear_transform() {
// @@protoc_insertion_point(one_of_clear_start:idtxcore.TransformUpdate)
  switch (transform_case()) {
    case kSeperate: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.transform_.seperate_;
      }
      break;
    }
    case kMatrix: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.transform_.matrix_;
      }
      break;
    }
    case TRANSFORM_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = TRANSFORM_NOT_SET;
}


void TransformUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:idtxcore.TransformUpdate)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.session_id_.ClearToEmpty();
  _impl_.usd_file_.ClearToEmpty();
  _impl_.prim_path_.ClearToEmpty();
  _impl_.timestamp_ = int64_t{0};
  clear_transform();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransformUpdate::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string session_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_session_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "idtxcore.TransformUpdate.session_id"));
        } else
          goto handle_unusual;
        continue;
      // string usd_file = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_usd_file();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "idtxcore.TransformUpdate.usd_file"));
        } else
          goto handle_unusual;
        continue;
      // string prim_path = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_prim_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "idtxcore.TransformUpdate.prim_path"));
        } else
          goto handle_unusual;
        continue;
      // .idtxcore.SeparateTransform seperate = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_seperate(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .idtxcore.Matrix4dTransform matrix = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_matrix(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TransformUpdate::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:idtxcore.TransformUpdate)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string session_id = 1;
  if (!this->_internal_session_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_id().data(), static_cast<int>(this->_internal_session_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "idtxcore.TransformUpdate.session_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_session_id(), target);
  }

  // string usd_file = 2;
  if (!this->_internal_usd_file().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_usd_file().data(), static_cast<int>(this->_internal_usd_file().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "idtxcore.TransformUpdate.usd_file");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_usd_file(), target);
  }

  // string prim_path = 3;
  if (!this->_internal_prim_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_prim_path().data(), static_cast<int>(this->_internal_prim_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "idtxcore.TransformUpdate.prim_path");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_prim_path(), target);
  }

  // .idtxcore.SeparateTransform seperate = 4;
  if (_internal_has_seperate()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::seperate(this),
        _Internal::seperate(this).GetCachedSize(), target, stream);
  }

  // .idtxcore.Matrix4dTransform matrix = 5;
  if (_internal_has_matrix()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::matrix(this),
        _Internal::matrix(this).GetCachedSize(), target, stream);
  }

  // int64 timestamp = 7;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(7, this->_internal_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:idtxcore.TransformUpdate)
  return target;
}

size_t TransformUpdate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:idtxcore.TransformUpdate)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string session_id = 1;
  if (!this->_internal_session_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_id());
  }

  // string usd_file = 2;
  if (!this->_internal_usd_file().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_usd_file());
  }

  // string prim_path = 3;
  if (!this->_internal_prim_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_prim_path());
  }

  // int64 timestamp = 7;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  switch (transform_case()) {
    // .idtxcore.SeparateTransform seperate = 4;
    case kSeperate: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.transform_.seperate_);
      break;
    }
    // .idtxcore.Matrix4dTransform matrix = 5;
    case kMatrix: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.transform_.matrix_);
      break;
    }
    case TRANSFORM_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransformUpdate::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TransformUpdate::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransformUpdate::GetClassData() const { return &_class_data_; }


void TransformUpdate::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TransformUpdate*>(&to_msg);
  auto& from = static_cast<const TransformUpdate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:idtxcore.TransformUpdate)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_session_id().empty()) {
    _this->_internal_set_session_id(from._internal_session_id());
  }
  if (!from._internal_usd_file().empty()) {
    _this->_internal_set_usd_file(from._internal_usd_file());
  }
  if (!from._internal_prim_path().empty()) {
    _this->_internal_set_prim_path(from._internal_prim_path());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  switch (from.transform_case()) {
    case kSeperate: {
      _this->_internal_mutable_seperate()->::idtxcore::SeparateTransform::MergeFrom(
          from._internal_seperate());
      break;
    }
    case kMatrix: {
      _this->_internal_mutable_matrix()->::idtxcore::Matrix4dTransform::MergeFrom(
          from._internal_matrix());
      break;
    }
    case TRANSFORM_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TransformUpdate::CopyFrom(const TransformUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:idtxcore.TransformUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransformUpdate::IsInitialized() const {
  return true;
}

void TransformUpdate::InternalSwap(TransformUpdate* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.session_id_, lhs_arena,
      &other->_impl_.session_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.usd_file_, lhs_arena,
      &other->_impl_.usd_file_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.prim_path_, lhs_arena,
      &other->_impl_.prim_path_, rhs_arena
  );
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
  swap(_impl_.transform_, other->_impl_.transform_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata TransformUpdate::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_transform_2eproto_getter, &descriptor_table_transform_2eproto_once,
      file_level_metadata_transform_2eproto[3]);
}

// ===================================================================

class TransformBroadcast::_Internal {
 public:
  static const ::idtxcore::TransformUpdate& update(const TransformBroadcast* msg);
};

const ::idtxcore::TransformUpdate&
TransformBroadcast::_Internal::update(const TransformBroadcast* msg) {
  return *msg->_impl_.update_;
}
TransformBroadcast::TransformBroadcast(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:idtxcore.TransformBroadcast)
}
TransformBroadcast::TransformBroadcast(const TransformBroadcast& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TransformBroadcast* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.client_id_){}
    , decltype(_impl_.update_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.client_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_client_id().empty()) {
    _this->_impl_.client_id_.Set(from._internal_client_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_update()) {
    _this->_impl_.update_ = new ::idtxcore::TransformUpdate(*from._impl_.update_);
  }
  // @@protoc_insertion_point(copy_constructor:idtxcore.TransformBroadcast)
}

inline void TransformBroadcast::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.client_id_){}
    , decltype(_impl_.update_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.client_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TransformBroadcast::~TransformBroadcast() {
  // @@protoc_insertion_point(destructor:idtxcore.TransformBroadcast)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TransformBroadcast::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.client_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.update_;
}

void TransformBroadcast::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TransformBroadcast::Clear() {
// @@protoc_insertion_point(message_clear_start:idtxcore.TransformBroadcast)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.client_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.update_ != nullptr) {
    delete _impl_.update_;
  }
  _impl_.update_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransformBroadcast::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string client_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_client_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "idtxcore.TransformBroadcast.client_id"));
        } else
          goto handle_unusual;
        continue;
      // .idtxcore.TransformUpdate update = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_update(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TransformBroadcast::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:idtxcore.TransformBroadcast)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_client_id().data(), static_cast<int>(this->_internal_client_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "idtxcore.TransformBroadcast.client_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_client_id(), target);
  }

  // .idtxcore.TransformUpdate update = 2;
  if (this->_internal_has_update()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::update(this),
        _Internal::update(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:idtxcore.TransformBroadcast)
  return target;
}

size_t TransformBroadcast::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:idtxcore.TransformBroadcast)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_client_id());
  }

  // .idtxcore.TransformUpdate update = 2;
  if (this->_internal_has_update()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.update_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransformBroadcast::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TransformBroadcast::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransformBroadcast::GetClassData() const { return &_class_data_; }


void TransformBroadcast::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TransformBroadcast*>(&to_msg);
  auto& from = static_cast<const TransformBroadcast&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:idtxcore.TransformBroadcast)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_client_id().empty()) {
    _this->_internal_set_client_id(from._internal_client_id());
  }
  if (from._internal_has_update()) {
    _this->_internal_mutable_update()->::idtxcore::TransformUpdate::MergeFrom(
        from._internal_update());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TransformBroadcast::CopyFrom(const TransformBroadcast& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:idtxcore.TransformBroadcast)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransformBroadcast::IsInitialized() const {
  return true;
}

void TransformBroadcast::InternalSwap(TransformBroadcast* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.client_id_, lhs_arena,
      &other->_impl_.client_id_, rhs_arena
  );
  swap(_impl_.update_, other->_impl_.update_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TransformBroadcast::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_transform_2eproto_getter, &descriptor_table_transform_2eproto_once,
      file_level_metadata_transform_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace idtxcore
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::idtxcore::Vector3*
Arena::CreateMaybeMessage< ::idtxcore::Vector3 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::idtxcore::Vector3 >(arena);
}
template<> PROTOBUF_NOINLINE ::idtxcore::Matrix4dTransform*
Arena::CreateMaybeMessage< ::idtxcore::Matrix4dTransform >(Arena* arena) {
  return Arena::CreateMessageInternal< ::idtxcore::Matrix4dTransform >(arena);
}
template<> PROTOBUF_NOINLINE ::idtxcore::SeparateTransform*
Arena::CreateMaybeMessage< ::idtxcore::SeparateTransform >(Arena* arena) {
  return Arena::CreateMessageInternal< ::idtxcore::SeparateTransform >(arena);
}
template<> PROTOBUF_NOINLINE ::idtxcore::TransformUpdate*
Arena::CreateMaybeMessage< ::idtxcore::TransformUpdate >(Arena* arena) {
  return Arena::CreateMessageInternal< ::idtxcore::TransformUpdate >(arena);
}
template<> PROTOBUF_NOINLINE ::idtxcore::TransformBroadcast*
Arena::CreateMaybeMessage< ::idtxcore::TransformBroadcast >(Arena* arena) {
  return Arena::CreateMessageInternal< ::idtxcore::TransformBroadcast >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
